config/redirects_unicorn-utterances.com
gatsby-config.js
package.json
src/data/unicorns.json
src/pages/about.js

rm console, rm blurbet, move repo URL, add nginx

---

content/blog/angular-templates-start-to-source/index.md
content/blog/uttering-hello-introduction-post/index.md
gatsby-config.js
src/components/layout/layout.js
src/data/licenses.json
src/templates/blog-post.js

Fixes #8
There should be a new issue assigned to generate a template of these LICENSES for the `.txt` to be downloaded on a per-post basis. Until then, this should suffice

Added license support in the UI, added licenses to posts

---

package-lock.json
src/components/layout/layout.js
src/data/unicorns.json

I had previously typed the wrong link for Tom's twitter and, though the UI was setup, I did not update the GraphQL call to include the website link. This PR fixes both

Fix Tom Twitter link, fix website display

---

.travis.yml
README.md

This adds a travis config to do our tests and build on all PRs

Added initial travis integration

---

src/_vars.scss
src/components/filter-search-bar/filter-listbox/filter-listbox.module.scss
src/components/filter-search-bar/filter-search-bar.module.scss
src/components/filter-search-bar/search-field/search-field.module.scss
src/components/pic-title-header/pic-title-header.module.scss
src/components/post-card-list/post-card-list.module.scss
src/components/post-view/post-metadata/post-metadata.js
src/components/post-view/post-metadata/post-metadata.module.scss
src/components/post-view/post-title-header/post-title-header.module.scss
src/global.scss
src/pages/about.js
src/pages/about.module.scss

This PR does some initial work to improve mobile styling and consolidating of the media queries used to make mobile styling work
Something that @tommyemo pointed out is that it does not match his mobile mockup for the posts properly - this is something we'll want to address in a (close-to-now) PR with him (which I intend to be doing later in the next week)

Initial mobile styling

---

content/assets/branding/emotes/README.md

Pretty self-explanatory, makes it looks nice.

Changed order of emotes in README so that it makes a rainbow

---

src/components/filter-search-bar/filter-listbox/filter-listbox.module.scss
src/components/filter-search-bar/filter-search-bar.module.scss
src/components/filter-search-bar/search-field/search-field.module.scss

Everything seems to work fine but I feel like there might still be some issues lurking. Hopefully this can work as a short-term fix.

Fixed some spacing issues (as well as #28) with filter/search

---

src/utils/useLunr.js

This PR is a temporary fix. It adds too many results - I'm finding that I don't know Lunr well enough to fix the issues with the site long-term

Lazy fix of full results in Lunr

---

src/data/unicorns.json

> 🎵 You change your handle  🎵
> 🎵 Like a girl changes clothes 🎵

Update Evelyn's Twitter handle

---

content/blog/typescript-type-generics/index.md

Any feedback (tone, grammar, spelling, etc) hugely welcome. I'm excited to go through the first open dialog regarding a PR for a post! :D

Added typescript generics post

---

src/_vars.scss
src/components/filter-search-bar/filter-listbox/filter-listbox.module.scss
src/components/filter-search-bar/filter-search-bar.module.scss
src/components/filter-search-bar/search-field/search-field.module.scss
src/components/pic-title-header/pic-title-header.module.scss
src/components/post-card-list/post-card-list.module.scss
src/components/post-view/post-metadata/post-metadata.module.scss
src/components/post-view/post-title-header/post-title-header.module.scss
src/global.scss
src/pages/404.js
src/pages/about.module.scss
src/templates/blog-post.js

Minor Bug Fixes

---

content/blog/angular-templates-start-to-source/index.md
content/blog/introduction-to-typescript/index.md

Thanks for noticing this and proposing the fix @adueppen :heart:

Fix: Fixed and added missing code syntax tags in posts

---

package-lock.json

This [apparently fixes 16K+ vulnerabilities in only 7 package changes](https://user-images.githubusercontent.com/38994283/67547203-447afb00-f6b3-11e9-8a0a-dcaf76f39e2e.png) 🤔

Upgrade: npm audit fix

---

content/blog/understanding-the-dom/index.md

This PR includes a change to the `Understanding the DOM` post that now references the new post that's being added in #127

Updated "Understanding the DOM" to include cross-ref with #127

---

src/components/post-card/post-card.module.scss
src/global.scss

- Line height 1.7 for post body and post card, 1.5 for headings
- Asymmetrical heading margins as is standard for technical documents
- Symmetrical if headings are adjacent siblings

Update: post body line height and heading margins

---

src/components/filter-search-bar/filter-listbox/filter-listbox.tsx

Fix list being read when collapsed

---

CONTRIBUTING.md
README.md

Previously, we didn't have a good set of documentation for how to contribute to the project for newcomers. This PR thoroughly introduces the documentation. I'll grant that it's a bit long, but that's because I wanted to touch base on the various means to contribute we offer

Added Contributing file

---

content/blog/ultimate-windows-development-environment-guide/index.md

Various commenters on the site informed me of various things that should be added/updated. Thanks to:
- http://disq.us/p/28goni5
- http://disq.us/p/28gmuxc
- http://disq.us/p/28hf8ij
- http://disq.us/p/28grwl8

Windows Blog: Added Awesome Windows, WSL.exe, other terminal, more

---

content/blog/ultimate-windows-development-environment-guide/index.md

Add ChocolateyGUI install instructions

---

content/blog/five-suggestions-for-simpler-tests/index.md

Written between @skatcat31 and myself, this article outlines five methods to make your integration testing easier and better.

Simpler tests post

---

content/blog/writing-better-angular-tests/index.md

edits are self explanatory. There was mentions of an edit meta data?

update the testing article to allow for `ng test`

---

content/blog/setup-standard-version/index.md
gatsby-config.js

Everything from #243 looks good!
Behind the scenes changes:
- Bumped down `/page-data/*` caching to max-age of 0 in `beta`
- Added both caching policies to production

Integration merge 06/30/2020

---

content/data/unicorns.json

Updated my website and LinkedIn ID

---

package-lock.json
package.json
src/components/filter-search-bar/filter-listbox/filter-listbox.tsx
src/components/filter-search-bar/search-field/search-field.tsx

This PR migrates away from `react-pose`  as it's now depreciated. Replaced with `framer-motion` per #268.
Closes #268.

Replace `react-pose` with `framer-motion`

---

.github/workflows/deploy-beta.yml
.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/destroy-dev.yml
.github/workflows/test.yml

chore: upgrade Node.js, actions, and increase sync retries for backoff

---

content/site/about-us.md

Opening this to make it more obvious what each sponsor does any why.
Let me know what you think of the language. 
Closes #284

Disclose sponsor relationships in about page

---

src/constants/search-and-filter-context/search-and-filter-context.ts
src/utils/debounce.ts

This PR adds in analytics support for search and filter.
The primary motivation for doing so is that I'd like to see if users are actually utilizing these features, and if so, what for? 
This should help us understand if we need to spend more time on search/filtering and potentially add in server-side support for better search or if this wouldn't be beneficial for our users
Open for discussion about the potential privacy implications and what we should do with this

Add search and filter analytics

---

src/components/seo.tsx
src/constants/site-url.js
src/page-components/post-list/post-list-header/post-list-header.tsx
src/page-components/unicorns/profile-header/profile-header.tsx
src/pages/404.tsx
src/pages/about.tsx
src/pages/confirm.tsx
src/pages/posts/[slug].tsx
src/pages/thanks.tsx
src/pages/unicorns/[...pageInfo].tsx

This PR:
- Fixes LCP issues with top-of-fold images
- Improves `og:url` tag
- Fixes SEO loading between client refreshes

Various site fixes

---

src/components/dark-light-button/dark-light-button.tsx
src/components/filter-search-bar/filter-listbox/filter-listbox.tsx
src/page-components/post-list/post-list-header/post-list-header.tsx

A11y fixes for homepage

---

src/shiki.scss

This PR adds in line numbers to all code samples

feat: add in code line numbers

---

src/page-components/about/about-us-translations-header/about-us-translations-header.module.scss
src/page-components/about/about-us-translations-header/about-us-translations-header.tsx
src/page-components/about/about-us-translations-header/index.ts
src/page-components/blog-post/translations-header/translations-header.tsx
src/pages/about.tsx

About us i18n

---

package-lock.json
package.json
src/build-scripts/generate-epubs.ts
src/utils/markdown/unified-chain.ts
src/utils/markdown/useMarkdownRenderer.tsx
src/utils/url-paths.ts

Previously, when trying to open a generated epub from various sources, it would error out as we had epub validation errors.
This PR fixes those validation errors and makes each generated epub valid

Fix epub validity

---

content/data/languages.json
content/data/unicorns.json
content/site/about-us.fr.md

Also changed a paragraph in the English version

Added French Translation of About Us page

---

content/site/about-us.es.md

Translated about us aria labels into Spanish

---

content/blog/angular-extend-class/index.md

- Fix broken link to dependency injection section.

fix: fix broken section link

---

content/blog/angular-extend-class/index.md

When writing the article originally, I didn't realize that `@Injectable`s had the ability to use `OnDestroy` (despite @LayZeeDK's best efforts)
This PR updates the article to more accurately reflect what a better fix for the cleanup logic looks like

chore: replace manual cleanup calls with ngOnDestroy usage

---

src/styles/iframe-replacement.scss
src/styles/post-body.scss
src/utils/markdown/constants.ts
src/utils/markdown/rehype-unicorn-iframe-click-to-run.ts
src/utils/markdown/scripts/iframe-click-to-run.ts

Reverts unicorn-utterances/unicorn-utterances#477, yay

Revert "Revert "Fix iframe embed placeholder size""

---

api/.gitignore
api/package-lock.json
api/package.json
api/search.ts
build-scripts/search-index.ts
package.json
src/components/filter-search-bar/filter-search-bar.astro
src/pages/unicorns/unicornProfilePicMap.json.ts

- Creates a separate `package.json` for the search API dir
- Moves the generated `searchIndex.json` into `/api`
- Adds a `/unicorns/unicornProfilePicMap.json` to the Astro build
- Modifies the search page to fetch `/unicorns/unicornProfilePicMap.json` instead of expecting it from the search response

Fix search api endpoint

---

content/blog/advice-for-new-twitch-streamers/index.md

fix some typos

---

content/blog/twitch-chatbot-in-bash/index.md

take away my bash privileges, i've been spreading false truths on the internet :(

add a missing # NotLikeThis

---

src/components/pagination/pagination.module.scss
src/components/pagination/pagination.tsx

This PR fixes the pagination styling broken by #539

[UWU] Make pagination buttons match spec

---

src/page-components/collections/framework-field-guide/segments/your-guide.astro

Your Guide section in FFG grew so much as I'm now a maintainer of [Jimp](https://www.npmjs.com/package/jimp)

chore: update Corbin PFP and Your Guide

---

src/assets/unicorn_happy.svg
src/assets/unicorn_neutral.svg
src/assets/unicorn_sad.svg
src/components/page-card/page-card.astro
src/components/page-card/page-card.module.scss
src/pages/404.astro
src/pages/confirm.astro
src/pages/thanks.astro

Currently, this PR only has one breakpoint for desktop on the 404 page:
I need to:

[UWU] Implement new 404, Thanks, and Confirm Pages

---

src/components/collection-card/collection-card.astro
src/components/collection-card/collection-card.module.scss

This PR updates the collection cards to match spec a bit better.

[UWU] Collection Cards to match Spec

---

src/views/blog-post/blog-post-layout/blog-post-layout.astro
src/views/blog-post/blog-post-layout/blog-post-layout.module.scss

This PR makes the sizing of the blog post layout screen more closely match the mockups

[UWU] update blog post layout screen

---

public/icons/arrow.svg
public/icons/dot.svg
src/utils/markdown/index.ts
src/utils/markdown/rehype-header-text.ts
src/views/blog-post/blog-post-layout/blog-post-layout.astro
src/views/blog-post/blog-post-layout/blog-post-layout.module.scss
src/views/blog-post/blog-post.astro
src/views/blog-post/table-of-contents/table-of-contents.astro
src/views/blog-post/table-of-contents/table-of-contents.module.scss

Preview: https://unicorn-utterances-git-uwu-toc-component-oceanbit.vercel.app/posts/object-mutation

[UWU] TOC Component Redesign

---

src/styles/markdown/hints.scss
src/views/blog-post/table-of-contents/table-of-contents.module.scss

Builds on `uwu-table` (#566 should be merged first)
- Fixes missing max-width on hints
- Fixes missing transition on hints
- Adds missing transition on table of contents items

[UwU] Various component fixes

---

src/styles/markdown/blockquote.scss
src/styles/post-body.scss

Implements blockquote styles/tokens
https://unicorn-utterances-git-uwu-blockquote-oceanbit.vercel.app/posts/minecraft-data-packs-scoreboards#Using-the-execute-store-subcommand

[UwU] Blockquote styling

---

src/styles/post-body.scss
src/views/blog-post/blog-post.astro
src/views/blog-post/post-title-header/post-title-header.astro
src/views/blog-post/post-title-header/post-title-header.module.scss

- Implement styling for article headers/metadata
https://unicorn-utterances-git-uwu-article-header-oceanbit.vercel.app/posts/unraveling-the-magic-of-the-virtual-dom

[UwU] Article header styling

---

src/components/chip/chip.module.scss
src/components/pagination/pagination.module.scss
src/components/post-card/post-card.module.scss
src/components/post-card/post-card.tsx
src/styles/button.scss
src/styles/markdown/tooltips.scss
src/types/PostInfo.ts
src/utils/data.ts
src/utils/markdown/rehype-word-count.ts
src/views/blog-post/post-title-header/post-title-header.module.scss
src/views/explore/homepage.astro

This PR:
- Updates the card's styling to match the spec
- Updates all usages of the dense icon to include the intended padding
- Fixes the focus state of chips using `outline` rather than a border

[UwU] Update Post Cards to match Spec

---

src/views/collections/collection-chapter.module.scss
src/views/collections/collection-page.module.scss

[UwU] fix collections small screen

---

src/components/post-card/post-card.tsx
src/utils/navigation-path-script.ts
src/views/collections/collection-chapter.astro
src/views/collections/collection-page.astro
src/views/explore/homepage.astro
src/views/explore/page.astro
src/views/unicorn/unicorn-page.astro

[UwU] Post card ctrl click

---

src/components/banner-stickers/banner-stickers-group.astro
src/components/banner-stickers/banner-stickers-mobile.astro
src/components/banner-stickers/banner-stickers.ts
src/components/hero/hero.astro
src/components/hero/hero.module.scss
src/views/base/navigation/header.module.scss

Implements the stickers banner on mobile

[UwU] Mobile stickers banner breakpoint

---

__mocks__/imports/svg-comp-mock.ts
__mocks__/imports/svg-raw-mock.ts
__mocks__/jest.setup.js
jest.config.cjs
package-lock.json
package.json
src/components/pagination/on-click-base.ts
src/components/pagination/pagination-popover.test.tsx
src/components/pagination/pagination-popover.tsx
src/components/pagination/pagination.test.tsx
src/components/pagination/pagination.tsx
src/components/pagination/types.ts
src/components/pagination/use-pagination.test.ts
src/components/pagination/use-pagination.ts
src/styles/button.scss

- Fixes pagination component creating extra buttons when there are fewer pages than `PAGE_BUTTON_COUNT`
- Fixes the pagination popup navigating to `/NaN` when its input is empty
- Fixes missing disabled styling on the pagination popup +/- buttons
- Adds unit tests for pagination logic

[UwU] Pagination logic fixes & unit tests

---

src/types/disqus.d.ts
src/types/ffg.d.ts
src/types/modules/gatsby-remark-embedder.d.ts
src/views/base/navigation/dark-light-button/theme-toggle.ts

This PR removes two TS types that were unused, and fixes various Disqus typings

[UwU] Remove unused types, fix Disqus types

---

content/blog/port-nextjs-to-astro/index.md

This PR updates the quote syntax to match our MD syntax in the Port to Astro article

fix: update the quote to MD syntax

---

src/page-components/collections/framework-field-guide/segments/quotes.astro
src/page-components/collections/framework-field-guide/segments/what-do-i-get.astro
src/page-components/collections/framework-field-guide/segments/what-do-i-get.module.scss
src/page-components/collections/framework-field-guide/segments/why-learn-all-three.astro
src/page-components/collections/framework-field-guide/segments/why-learn-all-three.module.scss
src/page-components/collections/framework-field-guide/styles/global-ffg.css
src/page-components/collections/framework-field-guide/tokens/dimensions.scss
src/page-components/collections/framework-field-guide/utils/weighted-random.ts
src/pages/collections/framework-field-guide/index.astro

Preview: https://unicorn-utterances-git-ffg-updates-oceanbit.vercel.app/collections/framework-field-guide
This PR:

FFG Updates

---

content/data/unicorns.json
src/page-components/collections/framework-field-guide/segments/pricing.module.scss
src/page-components/collections/framework-field-guide/segments/your-guide.astro
src/page-components/collections/framework-field-guide/segments/your-guide.module.scss

Preview: https://unicorn-utterances-git-ffg-updates-title-oceanbit.vercel.app/collections/framework-field-guide#your-guide

FF Add Title to Author Section

---

src/assets/unicorn_scared.svg
src/components/banner-stickers/banner-stickers-group.astro
src/styles/button.scss
src/views/search/components/filter-display.tsx
src/views/search/components/filter-sidebar.module.scss
src/views/search/components/filter-sidebar.tsx
src/views/search/components/search-hero.module.scss
src/views/search/components/search-hero.tsx
src/views/search/search-page.tsx

> This PR builds on top of #601 and #630, merge those first
This PR introduces the search states for the search page, like so:

[UwU] Search states

---

src/views/search/components/search-hero.module.scss

[UwU] Fix search state max width

---

__mocks__/data/mock-collection.ts
__mocks__/jest.setup.js
jest.config.cjs
package-lock.json
package.json
src/components/button-radio-group/button-radio-group.tsx
src/components/image/picture.tsx
src/components/pagination/pagination.tsx
src/components/pagination/types.ts
src/components/subheader/subheader.tsx
src/utils/search.ts
src/views/search/components/filter-section-item.tsx
src/views/search/components/filter-section.tsx
src/views/search/components/filter-sidebar.tsx
src/views/search/components/search-topbar.tsx
src/views/search/search-page.spec.tsx
src/views/search/search-page.tsx

This PR implements initial scaffolding (and many first tests) for the search page including:

[UwU] Search tests

---

__mocks__/jest.setup.js
src/utils/debounce.ts
src/views/search/search-page.spec.tsx
src/views/search/search-page.tsx
src/views/search/use-search-params.ts

This PR implements fixes to the back button on the search page, and includes tests to validate this fix works as-intended

[UwU] Search fix back button

---

__mocks__/data/mock-collection.ts
content/blog/minecraft-data-packs-cmd-syntax/index.md
content/blog/minecraft-data-packs-introduction/index.md
content/blog/minecraft-data-packs-scoreboards/index.md
content/collections/minecraft-data-packs/index.md
content/collections/web-components-101/index.md
content/data/tags.json
src/components/post-card/post-card.tsx
src/components/search-section/search-section.astro
src/types/CollectionInfo.ts
src/utils/data.ts
src/views/search/components/filter-display.tsx
src/views/search/components/search-hero.module.scss
src/views/search/search-page.tsx
src/views/unicorn/unicorn-page.astro

[UwU] Fix minor search issues

---

src/views/explore/homepage.astro
src/views/search/search-page.tsx

[UwU] More small search fixes

---

src/components/search-section/search-section.astro

This PR implements the home search box

[UwU] Hook up home search box

---

content/data/tags.json
public/stickers/minecraft.svg

This PR adds a sticker for Minecraft

[UwU] MC Sticker

---

src/views/blog-post/blog-post.astro
src/views/blog-post/blog-post.module.scss

This PR implements the article footer as it is seen in the Figma
Fixes #595

[UwU] Fix article footer

---

src/components/button-radio-group/button-radio-group.tsx
src/components/select/select.tsx
src/views/search/components/filter-display.tsx
src/views/search/components/filter-sidebar.module.scss
src/views/search/components/filter-sidebar.tsx
src/views/search/components/search-topbar.tsx
src/views/search/components/types.ts
src/views/search/search-page.spec.tsx
src/views/search/search-page.tsx

[UwU] Change search button groups to select

---

content/blog/minecraft-data-packs-introduction/index.md

Updates the Minecraft data packs introduction with new version numbers & replaces code blocks with the file tree component

MC introduction updates

---

src/styles/markdown/lists.scss
src/styles/markdown/table.scss
src/styles/markdown/tabs.scss
src/styles/post-body.scss
src/utils/sticky-observer-script.ts
src/views/blog-post/blog-post-layout/blog-post-layout.module.scss

- Fixes the sidebar using an inconsistent max-height
- Removes duplicate margins for nested `ul`s
- Adds a margin to text within tab contents to prevent clipping - #612

[UwU] Various article spacing fixes

---

src/styles/shiki.scss

Preview: https://unicorn-utterances-git-uwu-fix-line-highlight-oceanbit.vercel.app/posts/port-nextjs-to-astro#Next-base-layout-to-Astro
Closes #692

[UwU] Fix line highlight

---

src/styles/post-body.scss

Not specced, this is just me messing around with things
https://unicorn-utterances-git-uwu-style-hr-oceanbit.vercel.app/posts/setup-a-react-native-monorepo

[UwU] `<hr>` styling

---

src/views/about/contributor-card.astro
src/views/about/contributor-card.module.scss

- Updates the contributor card layout
https://unicorn-utterances-git-uwu-contributor-card-oceanbit.vercel.app/about

[UwU] Update contributor card design

---

src/styles/post-body.scss

Updates inline code to match #710

[UwU] Update inline code styling

---

src/components/pagination/pagination.module.scss

[UwU] Fix pagination focus styling

---

src/styles/markdown/tabs.scss

[UwU] Fix tab inner margin not applying to certain elements

---

src/components/related-posts/related-posts.astro
src/pages/index.astro
src/views/blog-post/blog-post.astro
src/views/blog-post/table-of-contents/table-of-contents.astro

[UwU] Landmark A11Y fixes

---

astro.config.ts
src/components/seo/locale.astro
src/components/seo/seo.astro
src/pages/[...locale]/about.astro
src/pages/[...locale]/collections/[slug].astro
src/pages/[...locale]/posts/[postid].astro
src/utils/translations.ts

[UwU] Locale fixes

---

src/views/collections/framework-field-guide/segments/code-block.scss

[UwU] Fix FFG tabs

---

src/views/search/components/filter-section-item.tsx
src/views/search/components/filter-section.module.scss
src/views/search/components/filter-section.tsx
src/views/search/components/filter-sidebar.tsx

> This PR builds on top of #769, please merge that first
This PR fixes #752

[UwU] Improve sidebar accessibility reading

---

src/styles/shiki.scss
src/styles/variables/colors.scss
src/styles/variables/themes.scss
src/views/base/navigation/header.module.scss

[UwU] Make colors more contrasted

---

src/utils/data.ts

[UwU] Fix about shiki

---

src/views/base/translations/translations-header.astro
src/views/base/translations/translations-header.module.scss

Add `aria-current="page"` to the translation header on the currently selected item

[UwU] Minor translation header a11y improvement

---

src/pages/[...locale]/collections/[slug].astro
src/pages/page/[page].astro
src/pages/unicorns/[unicornid]/index.astro
src/views/about/about.astro
src/views/about/banner-svg.astro
src/views/blog-post/blog-post.astro
src/views/collections/collection-page.astro
src/views/unicorn/components/profile-section.astro
src/views/unicorn/unicorn-page.astro

[UwU] Landmark improvements

---

jest.config.cjs
src/components/dialog/dialog.tsx
src/views/about/license.module.scss
src/views/about/license.tsx
src/views/search/components/filter-dialog.module.scss
src/views/search/components/filter-dialog.tsx

- Combines the two `<dialog>` element usages into one component to implement the modal behavior
- Enables clicking outside the search filter dialog in order to close/cancel it
- Fixes #732 
- Changes the dialog backdrop color per #783

[UwU] Search page dialog consistency

---

src/styles/post-body.scss

- Adds `:focus-visible` styling for `<a>` tags inside posts

[UwU] Add post-body <a> focus indicator styling

---

content/data/i18n/en.json
src/components/collection-card/collection-card.tsx
src/components/hero/hero.astro
src/components/hero/hero.module.scss
src/components/post-card/post-card-grid.tsx
src/components/post-card/post-card.module.scss
src/components/post-card/post-card.tsx
src/components/search-section/search-section.astro
src/components/select/select.tsx
src/global.scss
src/views/base/navigation/dark-light-button/dark-light-button.astro
src/views/collections/collection-chapter.astro
src/views/explore/homepage.astro
src/views/search/components/search-topbar.tsx
src/views/search/search-page.tsx
src/views/unicorn/components/achievement-card.astro
src/views/unicorn/components/profile-section.astro
src/views/unicorn/unicorn-page.astro

Fixes:
- #800 
- #802 
- #803 
- #804 
- #805 
- #808 
- #810

[UwU] Various site fixes

---

src/components/pagination/pagination-popover.module.scss
src/components/pagination/pagination-popover.tsx

Adds styling for the pagination popup focus state shown in #811

[UwU] Pagination popup focus styling

---

src/page-components/collections/framework-field-guide/segments/adventure-continues.astro
src/page-components/collections/framework-field-guide/segments/code-block.astro
src/page-components/collections/framework-field-guide/segments/ecosystem.astro
src/page-components/collections/framework-field-guide/segments/fundamentals.astro
src/page-components/collections/framework-field-guide/segments/hero.astro
src/page-components/collections/framework-field-guide/segments/internals.astro
src/page-components/collections/framework-field-guide/segments/pricing.astro
src/page-components/collections/framework-field-guide/segments/quotes.astro
src/page-components/collections/framework-field-guide/segments/sign-up.astro
src/page-components/collections/framework-field-guide/segments/what-do-i-get.astro
src/page-components/collections/framework-field-guide/segments/why-learn-all-three.astro
src/page-components/collections/framework-field-guide/segments/your-guide.astro

Add aria-labelledby to FFG section headers

---

src/styles/markdown/blockquote.scss

Preview: /posts/setup-a-react-native-monorepo

[UwU] Fix tweet embed styling

---

content/blog/port-nextjs-to-astro/index.md

Many of these highlights were off by 1, this fixes that

[UwU] Astro article highlights corrections

---

content/blog/angular-constructor-error-behavior/index.md

Fix typo in angular error behavior post description

---

src/components/input/input.module.scss

- Fix search caret color not displaying correctly on dark theme
- Fixes #822

[UwU] Fix search caret color

---

src/utils/markdown/iframes/rehype-transform.ts
src/utils/markdown/remark-embedder-twitch.ts

Changes any "clips.twitch.tv" URL to the correct twitch embed URL format.
Fixes #829

[UwU] Fix twitch clip player embedder

---

src/utils/markdown/index.ts

Fixes tab headings being included in the table of contents because of incorrect plugin order.

[UwU] Fix ToC tab headings

---

src/views/blog-post/table-of-contents/table-of-contents.module.scss

fix: table of contents needs proper bottom padding

---

src/views/blog-post/series/series-toc.module.scss

Adds focus styling for post chapter items:
https://unicorn-utterances-git-post-series-focus-styles-oceanbit.vercel.app/posts/what-is-reactivity

Add focus background/outline styling for post chapter items

---

src/utils/achievements/github.ts

Fixes a build error when GitHub logins do not return a valid user from the GraphQL API.

Fix GraphQL partial errors during build

---

src/views/collections/framework-field-guide/segments/fundamentals.astro
src/views/collections/framework-field-guide/segments/hero.astro
src/views/collections/framework-field-guide/segments/internals.astro
src/views/collections/framework-field-guide/segments/pricing.astro
src/views/collections/framework-field-guide/segments/your-guide.astro

Now that the book is mostly done, include the final wordcount.
I also got involved in TanStack pretty heavily, so update the NPM install count as well as the other metrics
Finally, I want to disable early access until final launch to keep the hype levels relatively high

chore: update FFG website with new numbers and better links

---

src/pages/collections/framework-field-guide/index.astro
src/views/collections/framework-field-guide/segments/support-me.astro
src/views/collections/framework-field-guide/segments/support-me.module.scss
src/views/collections/framework-field-guide/segments/your-guide.astro

feat: add a new section to donate to the FFG site

---

content/crutchcorn/posts/async-and-promises/index.md

This PR fixes some minor grammatical errors and typos I happened upon while reading @crutchcorn 's latest post

Minor grammar/typo fixes

---

content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-intro-to-components/index.md

Fixes accidentally typed ` character

Typo in event binding section

---

src/components/seo/seo.astro
src/pages/atom.xml.ts
src/pages/feed.json.ts

- adds atom and json feeds alongside rss feeds for convenience
- adds post excerpt as content alongside post description
- fixes incorrect feedLinks configuration preventing selflink within rss feed
- adds links to seo component for feed autodiscovery

Add Atom and JSON feeds with autodiscovery

---

content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-side-effects/index.md

Fix typo `unUnmounted` with `onUnmounted`

Fix typo in Vue code

---

content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-intro-to-components/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-side-effects/index.md

This PR fixes two typos I was brought attention to recently

docs: fix minor typos in FFG

---

content/crutchcorn/posts/javascript-functions-are-values/index.md

This PR fixes a typo in a few code samples here

docs: fix function articles

---

content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-element-reference/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-transparent-elements/index.md

docs: remove dead article reference

---

src/utils/markdown/iframes/rehype-transform.ts

I noticed that Node was failing in this branch due to no directory being created before its usage. This PR fixes this.

chore: fix build in some instances of newer node

---

build-scripts/generate-epubs.ts
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-dependency-injection/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-derived-values/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-passing-children/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-portals/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-shared-component-logic/index.md
package.json
pnpm-lock.yaml
src/utils/markdown/components/rehype-transform.ts
src/utils/markdown/createEpubPlugins.ts
src/utils/markdown/createHtmlPlugins.ts

This PR:
- Adds ebook-only contents
- Edits book to remove those contents
- Replace all emoji in book with `""` for compatibility
- Makes `details` and `summary` more clearly visual in ebook
- Fixes LOC count gutter to 4 chars

Epub fixes v2

---

src/utils/fetch-page-html.ts

I noticed that some ePub links would randomly give me other languages. This PR fixes that and makes it harder to detect us as a bot.

chore: add Bot evasion and language acceptance to fetchPageHTML util

---

build-scripts/epubs/generate-epubs.ts
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-comparison-table/index.md

This PR updates the FFG ebook to use 3 columns instead of 4 for spacing constraints and readability:

chore: improve the FFG comparison table for ebooks

---

src/views/base/navigation/header.astro
src/views/base/navigation/header.module.scss
src/views/base/navigation/rebrand-announcement-banner/rebrand-announcement-banner.astro
src/views/base/navigation/rebrand-announcement-banner/rebrand-announcement-banner.module.scss

Preview:
> Images intentionally blurred to keep secret
This PR:

Branding announcement banner

---

CONTRIBUTING.md
content/crutchcorn/posts/github-copilot-wont-replace-devs/index.md
content/data/about.json
src/constants/site-config.ts

This PR updates more social media links to our new brand name

chore: update all social links

---

content/crutchcorn/posts/why-is-css-in-js-slow/index.md

fix: typo in posts/why-is-css-in-js-slow/index.md

---

content/ljtech/collections/web-fundamentals/posts/web-fundamentals-flexbox/index.md

fix: typos in `web-fundamentals-flexbox/index.md`

---

content/ljtech/collections/web-fundamentals/posts/understanding-the-dom/event-bubbling-demo/index.html
content/ljtech/collections/web-fundamentals/posts/understanding-the-dom/event-bubbling-demo/index.js
content/ljtech/collections/web-fundamentals/posts/understanding-the-dom/event-bubbling-demo/package.json
content/ljtech/collections/web-fundamentals/posts/understanding-the-dom/event-bubbling-demo/style.css
content/ljtech/collections/web-fundamentals/posts/understanding-the-dom/event-capture-demo/index.html
content/ljtech/collections/web-fundamentals/posts/understanding-the-dom/event-capture-demo/index.js
content/ljtech/collections/web-fundamentals/posts/understanding-the-dom/event-capture-demo/package.json
content/ljtech/collections/web-fundamentals/posts/understanding-the-dom/event-capture-demo/style.css
content/ljtech/collections/web-fundamentals/posts/understanding-the-dom/index.md

> This PR builds on #1159 to avoid merge conflicts
This PR is just #1158 but localizing our code

fix: linked a correct version of the stackblitz about event

---

content/rollbear/posts/a-forgotten-idiom-revisited-pass-key/index.md

First post on this platform. Let me know if there are things I should do differently.

[Blog Post] rollbear: pass-key-idiom revisited

---

content/data/about.json
src/views/about/components.tsx

Website bug: added icon and link to youtube

---

pnpm-lock.yaml

This fixes issues that some new contributors were running into

chore: regenerate lockfile

---

content/crutchcorn/collections/return-to-form/posts/angular-forms-intro/index.md

I mainly came to just change `FromsModule` to `FormsModule`, and then also found some other minor grammar issues while re-reading it.
cc @crutchcorn

fix: typo and grammar issues

---

src/views/search/components/filter-dialog.tsx
src/views/search/components/filter-display.tsx
src/views/search/components/filter-section-item.tsx
src/views/search/components/filter-sidebar.tsx
src/views/search/constants.ts
src/views/search/orama.tsx
src/views/search/search-page.spec.tsx
src/views/search/search-page.tsx

This PR adds functionality to enable hybrid search when a user types 3 or more words in the search bar. It deals with issue [#1256](https://github.com/playfulprogramming/playfulprogramming/issues/1256)

Enable Orama hybrid search in some searches

---

CONTRIBUTING.code.md

I was chatting with Corbin and suggested this is something we should have. 
There are many things that mid-to-senior devs might consider common sense, but this document is (somewhat opinionated) and intended for an engineer with less a few months worth of experience.
Someone who is at the very early stages of their "journey in the craft" but would like to try their hand at contributing.
That being said, there are some things that might be contentious:
1. The over-use of analogies to explain things..I don't mind reducing, or altering the use of analogies, but in my experience, they are a very good tool to help beginners understand concepts.
2. There are "pro-tips" scattered throughout the document, these are my opinions...but I have tried to base them (on what I believe) is best practice, …

Added code contribution guide

---

content/fennifith/posts/example/index.md
src/utils/footnote-smooth-scroll.ts
src/utils/smooth-scroll-for-anchors-to-current-page.ts
src/views/blog-post/blog-post.astro

fixes #1294 
This PR implements smooth scrolling for footnote refs and footnote backrefs
- prefers reduced motion
- history/url modification

footnote smooth scrolling

---

content/crutchcorn/posts/vue-as-prop/as-prop-1/.gitignore
content/crutchcorn/posts/vue-as-prop/as-prop-1/index.html
content/crutchcorn/posts/vue-as-prop/as-prop-1/package-lock.json
content/crutchcorn/posts/vue-as-prop/as-prop-1/package.json
content/crutchcorn/posts/vue-as-prop/as-prop-1/src/App.vue
content/crutchcorn/posts/vue-as-prop/as-prop-1/src/OurButton.vue
content/crutchcorn/posts/vue-as-prop/as-prop-1/src/main.ts
content/crutchcorn/posts/vue-as-prop/as-prop-1/vite.config.js
content/crutchcorn/posts/vue-as-prop/index.md

> This blog post references the one from #1287, please release that one first.

[Blog Post] Vue `as` prop

---

content/crutchcorn/posts/angular-why-no-template-casting/attribute-selector-1/.gitignore
content/crutchcorn/posts/angular-why-no-template-casting/attribute-selector-1/angular.json
content/crutchcorn/posts/angular-why-no-template-casting/attribute-selector-1/package-lock.json
content/crutchcorn/posts/angular-why-no-template-casting/attribute-selector-1/package.json
content/crutchcorn/posts/angular-why-no-template-casting/attribute-selector-1/src/index.html
content/crutchcorn/posts/angular-why-no-template-casting/attribute-selector-1/src/main.ts
content/crutchcorn/posts/angular-why-no-template-casting/attribute-selector-1/tsconfig.app.json
content/crutchcorn/posts/angular-why-no-template-casting/attribute-selector-1/tsconfig.json
content/crutchcorn/posts/angular-why-no-template-casting/index.md

> This blog post references the ones from #1287 and #1290, please release those first.

[Blog Post] Why Can't Angular Cast An Element to Another?

---

src/views/base/navigation/header.module.scss

Before: 
[Screencast from 2025-03-21 19-16-32.webm](https://github.com/user-attachments/assets/0f1891e5-23ce-4f69-9303-ceb519b4dd4c)
After fix: 
[Screencast from 2025-03-21 19-09-11.webm](https://github.com/user-attachments/assets/f97d1554-c826-49fd-92fe-ef25da99fb1e)

quick-fix: heading bottom border transition on scroll

---

content/crutchcorn/posts/layered-react-structure/index.md

fix: typos in `layered-react-structure/index.md`

---

content/crutchcorn/collections/art-of-accessibility/index.md
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-element-association/index.md
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-angular-input-comp-3/.gitignore
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-angular-input-comp-3/angular.json
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-angular-input-comp-3/package-lock.json
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-angular-input-comp-3/package.json
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-angular-input-comp-3/src/index.html
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-angular-input-comp-3/src/main.ts
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-angular-input-comp-3/tsconfig.app.json
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-angular-input-comp-3/tsconfig.json
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-react-input-comp-3/.gitignore
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-react-input-comp-3/index.html
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-react-input-comp-3/package-lock.json
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-react-input-comp-3/package.json
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-react-input-comp-3/src/main.jsx
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-react-input-comp-3/src/main.module.css
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-react-input-comp-3/vite.config.js
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-vue-input-comp-3/.gitignore
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-vue-input-comp-3/index.html
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-vue-input-comp-3/package-lock.json
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-vue-input-comp-3/package.json
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-vue-input-comp-3/src/App.vue
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-vue-input-comp-3/src/TextInput.vue
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-vue-input-comp-3/src/main.js
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/art-of-a11y-vue-input-comp-3/vite.config.js
content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-labels/index.md

Not a complete set of details about forms, but a good insight into more accessible labels for web.
Many many more details about how to build proper web forms to come in "The Form Club" book at a later date 🤫

[Blog Post] Art of A11Y: Labels

---

src/styles/markdown/table.scss
src/utils/markdown/components/link-preview/fetchPreviewForUrl.ts
src/views/blog-post/blog-post-layout/blog-post-layout.module.scss

Fixes #1331
Adjusts the mobile header z-index and catches additional filesystem errors in the link preview script.

Fix link preview z index

---

content/spencercolaco/posts/you-should-be-using-unitless-values-for-line-height/line-height-bad-example/index.html
content/spencercolaco/posts/you-should-be-using-unitless-values-for-line-height/line-height-bad-example/package-lock.json
content/spencercolaco/posts/you-should-be-using-unitless-values-for-line-height/line-height-bad-example/package.json
content/spencercolaco/posts/you-should-be-using-unitless-values-for-line-height/line-height-bad-example/styles.css
content/spencercolaco/posts/you-should-be-using-unitless-values-for-line-height/line-height-good-example/index.html
content/spencercolaco/posts/you-should-be-using-unitless-values-for-line-height/line-height-good-example/package-lock.json
content/spencercolaco/posts/you-should-be-using-unitless-values-for-line-height/line-height-good-example/package.json
content/spencercolaco/posts/you-should-be-using-unitless-values-for-line-height/line-height-good-example/styles.css

Fix for Stackblitz sandboxes. Please allow preview link to generate before merging so I can verify. Thanks!

[Blog Post] Hotfix - Line height article

---

content/crutchcorn/posts/react-write-hooks-from-scratch/index.md

[Blog Post] Let's Write React Hooks From Scratch

---

content/crutchcorn/collections/art-of-accessibility/posts/art-of-a11y-semantic-markup/index.md
content/crutchcorn/collections/framework-field-guide-ecosystem/posts/ffg-ecosystem-bundling/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals-v1-1/posts/ffg-fundamentals-v1-1-component-reference/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals-v1-1/posts/ffg-fundamentals-v1-1-dynamic-html/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals-v1-1/posts/ffg-fundamentals-v1-1-error-handling/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals-v1-1/posts/ffg-fundamentals-v1-1-portals/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals-v1-1/posts/ffg-fundamentals-v1-1-shared-component-logic/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals-v1-1/posts/ffg-fundamentals-v1-1-side-effects/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals-v1/posts/ffg-fundamentals-v1-component-reference/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals-v1/posts/ffg-fundamentals-v1-dynamic-html/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals-v1/posts/ffg-fundamentals-v1-error-handling/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals-v1/posts/ffg-fundamentals-v1-portals/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals-v1/posts/ffg-fundamentals-v1-shared-component-logic/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals-v1/posts/ffg-fundamentals-v1-side-effects/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-component-reference/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-error-handling/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-portals/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-shared-component-logic/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-side-effects/index.md
content/crutchcorn/posts/react-history-through-code/index.md
content/ljtech/collections/web-fundamentals/posts/understanding-the-dom/index.md

Fixes for embedded stackblitz projects/params

Fix stackblitz embeds

---

astro.config.ts
package.json
pnpm-lock.yaml
src/pages/confirm.astro
src/pages/sitemap-0.xml.ts
src/pages/sitemap-index.xml.ts
src/pages/thanks.astro
src/utils/api.ts

- Removes the `@astrojs/sitemap` plugin, and removes content references from astro.config.ts
- Adds dynamic routes for sitemap-index.xml and sitemap-0.xml
- Excludes `/confirm` and `/thanks` newsletter pages from the index

Dynamic sitemap routes

---

src/views/about/about.module.scss

CSS Specificity Strikes Again!

Fix about page banner scaling issue
