playfulprogramming/playfulprogramming

src/pages/index.js

This allows it to load in place instead of fully reloading the page.

Change about page link to a <Link> component

---

gatsby-config.js

Previously, we had `\/` hardcoded in a regex to inline SVGs. This would cause our dev and prod builds to fail on windows machines. This PR fixes this by adding an `or` condition to that merge request

Fix windows build

---

src/components/pic-title-header/pic-title-header.js

This makes sure the SVG attributes remain intact, critically including the class which is needed for some CSS rules.

Change social icons to components instead of functions

---

src/global.scss

For some reason Firefox has a somewhat different thing going on with the focus ring. This solution works fine on both Linux and Windows so far, which matters due to the fact that Firefox attempts to use native OS UI styles for things such as buttons.

Make sure focus ring has good contrast

---

config/jest/setup-test-env.js
package-lock.json
package.json
src/components/dark-light-button/dark-light-button.js
src/components/layout/layout.js
src/components/pic-title-header/pic-title-header.js
src/components/post-view/post-metadata/post-metadata.js
src/pages/__tests__/index.test.js
src/templates/blog-post.js
src/templates/blog-post.test.js
src/templates/blog-profile.test.js

This PR adds the axe-jest automated A11Y best-practices toolset. Now, when tests are ran, we can ensure that we're catching _some_ of the A11Y errors that might be introduced into a PR
This PR also fixes some of the axe errors that were present in our codebase
Keep in mind: These tests do not find all errors, just the best practices. Manually QA is still needed

Added jest-axe and fixed a11y axe warnings

---

content/blog/angular-templates-start-to-source/index.md

Having only one newline causes the markdown on the next line to not render correctly.
Replace: `/(?<=</iframe>)\n(?!\n)/` with `\n\n`

Fix: Add extra newline after inline iframes in Angular Templates Post

---

src/global.scss

Firefox supports the `scrollbar-color` property in CSS which allows the scrollbar to be easily themed. WebKit-based browsers have similar capabilities as well, so hopefully we can create a similar experience in both environments.

WIP Themed Scrollbar

---

src/components/filter-search-bar/filter-listbox/filter-listbox.js
src/components/layout/layout.js
src/components/pic-title-header/pic-title-header.js
src/components/pic-title-header/pic-title-header.module.scss
src/components/pic-title-header/pic-title-header.test.js
src/components/post-card-list/post-card-list.js
src/components/post-card-list/post-card-list.module.scss
src/components/post-card/post-card.js
src/components/post-view/post-title-header/post-title-header.js
src/components/post-view/post-title-header/post-title-header.module.scss
src/global.scss
src/pages/about.js
src/pages/index.js
src/templates/blog-post.js
src/templates/blog-profile.js
src/utils/useOutsideClick.js

This PR provides some fixes for A11Y on the site that does the following:
- Focuses the button on the listbox after escape is pressed
- Adds missing aria attributes for the filter listbox
- Change subheader on profile and about page from h2 to `aside` (which fits MUCH better for the UX of the page)
- Move profile social links to a `ul`
- Move the cards list to a `ul`

A11y fixes for filter, subheader, profile social links, and card list, etc

---

src/pages/about.js

Switch the `unicornRoles` variable to a copy of the role array instead of a reference. Closes #93

Fix author duplication bug

---

src/components/pic-title-header/pic-title-header.module.scss

Previously, the logo on the mainpage was centered to the left
With this PR, we've fixed centering the logo

Center the logo on mobile properly

---

src/global.scss

Heading anchor links are now vertically centered on the first line of the heading.
Its padding is converted to additional negative margin so that the headings are flush with the keyline.

Fix: autolink-headings anchors positioning

---

content/blog/angular-templates-start-to-source/index.md
gatsby-config.js
package-lock.json

I noticed a few small issues that seemed to be happening with syntax highlighting and code blocks in general, including a warning about prismjs not supporting Gradle yet. Aliasing it to Groovy manages to at least provide some basic highlighting.

Fix syntax highlighting

---

package.json

Found by @adueppen, the project had the incorrect package.json license field, which has now been updated

Update package license

---

src/templates/blog-post.js

I'll have to migrate the Disqus posts, but we were resetting the disqus identifier by the theme that was used to load it
https://sporadicallyyours.com/techbytes/2013/5/19/change-url-without-losing-comments

Fix disqus slug

---

src/templates/blog-post.js

Previously, we had issues where the comment url was matching to `unicorn-utterances.composts` instead of `unicorn-utterances.com/posts`. This PR fixes that

Fix comment URLs and comment loading

---

content/blog/intro-to-html-css-and-javascript/index.md

For all of our other posts, we have lowercase tags. Because of this post's deviance from that pattern, it was listing some of the values twice. 
Additionally, this removes one of the tags as it didn't seem to match up to an actual skillset someone might be searching for via tag search

Align post tags to be more inline with other posts

---

content/blog/hard-grids-and-baselines-android-design-fidelity/index.md
src/components/layout/layout.js

@PrattiDev, upon recieving a comment on it, realized that he wanted to add a mention of the API being backported. This adds the following to the post

Android post: Added mention of API backporting

---

src/components/pic-title-header/pic-title-header.module.scss

Includes `margin-right` in all screen size but not in small breakpoint.

Properly fix header logo

---

README.md

When we did work on #151, we didn't change the README symbols that were previously aligned with Travis CI. The new PR updates this badge to reflect our new CI integration

Update README GH Action badge

---

content/site/about-us.md
src/templates/post-list.test.tsx
src/templates/post-list.tsx

We previously did not include mention of our LinkedIn, Twitter, YouTube, or other avenues in our about page. This not only adds that but renames the confusingly explained "Learn more" link for a more self-explanitory "about us"

Include our social media links. Rename "Learn more" to "About us"

---

content/blog/angular-templates-start-to-source/index.md

Now that we have our YouTube channel up-and-running with the edited video uploaded, I've added a link to the YouTube video inside of the post's aside at the top of the article alongside mention of the slides

Add mention of the recorded talk on Angular templates

---

src/components/seo.tsx

This will fix the `og:img` issue for sites that do not infer the image from other meta tags or allow `name=` instead of `property`.
This patch will appear not to work on `beta.unicorn-utterances.com` before it goes live in prod because it uses the canonical URL of production.

Fix: Change open graph image meta tag to property from name

---

src/components/seo.tsx
src/pages/404.tsx
src/pages/about.tsx
src/templates/blog-post.tsx
src/templates/blog-profile.tsx

Fixes open graph metadata and social media engagement matching the homepage when sharing a post to Facebook, LinkedIn, etc.
- Sharing `https://unicorn-utterances.com/posts/how-to-pick-tech-stacks-for-new-projects/` will show the metadata and social media metrics for the post even if it's not an exact match
- Sharing `https://unicorn-utterances.com/page/2` will show the homepage metadata
This doesn't implement redirects/canonical URLs for renamed users or posts since we don't have any yet. [This is a future avenue to explore when needed](https://developers.facebook.com/docs/sharing/webmasters/getting-started/versioned-link/#preserve-engagement-metrics).

Fix: Open Graph canonical URL is post, author, or page URL

---

content/blog/angular-templates-start-to-source/index.md
content/blog/basic-overview-of-packets-and-osi/index.md
content/blog/intro-to-html-css-and-javascript/index.md
content/blog/introduction-to-typescript/index.md
content/blog/understanding-the-dom/index.md

Previously, we were treating internal links as "nofollow"s, which likely harmed our SEO. This should fix that and make them internal links again
This also adds a mention to the DOM post inside of the related Angular post

Fix internal links not to be external ones, added mention of DOM post

---

src/pages/confirm.tsx
src/pages/thanks.tsx

Fix image overflowing of confirm page

Fix `confirm` and `thanks` page image

---

src/components/filter-search-bar/filter-listbox/filter-listbox.module.scss
src/components/filter-search-bar/filter-listbox/filter-listbox.tsx

This PR addresses three issues with the filter dropdown:
1) The text was previously not vertically centered
|Before|After|
|---|---|
|![The text is not aligned vertically](https://user-images.githubusercontent.com/9100169/78744102-86bc8f80-7915-11ea-830e-09dc4e5daa5c.png)|![The text is now aligned](https://user-images.githubusercontent.com/9100169/78744110-91772480-7915-11ea-872b-10e4e28931b1.png)|
2) Anything with a lower-hanging letter (g, y, j, etc) was being cut off
|Before|After|
|---|---|
|![The lower-hanging letters are cut off](https://user-images.githubusercontent.com/9100169/78744155-b23f7a00-7915-11ea-898d-5ae0de11efa0.png)|![The letters are now displaying properly!](https://user-images.githubusercontent.com/9100169/78744179-c1262c80-7915-11ea-9977-fcfa91e9c021.png)|
3) The …

Made filter dropdown scroll, fix cut off text, fix text alignment

---

src/_vars.scss
src/components/mailing-list/mailing-list.scss
src/components/pic-title-header/pic-title-header.module.scss
src/components/post-card-list/post-card-list.module.scss
src/components/post-card/post-card.module.scss
src/components/post-view/post-metadata/post-metadata.module.scss
src/components/post-view/post-title-header/post-title-header.module.scss
src/components/table-of-contents/table-of-contents.module.scss
src/global.scss
src/pages/about.module.scss
src/prism.scss

@evelynhathaway messaged me directly to inform me of a critical A11Y issue: Our site did not respond to custom font sizes set in the browser. This should now be fixed - I've tested myself to good results:
|Font Setting|Before|After|
|---|---|---|
|Large|![The font size set to large before the fix](https://user-images.githubusercontent.com/9100169/78851894-ce9fed00-79cf-11ea-9635-911c9d6fd34e.png)|![The font size set to large after the fix](https://user-images.githubusercontent.com/9100169/78851906-db244580-79cf-11ea-9d78-225bdb51fb6d.png)|
|Small|![The font size set to small before the fix](https://user-images.githubusercontent.com/9100169/78851932-f4c58d00-79cf-11ea-9318-c35f4f548f49.png)|![The font size set to small after the fix](https://user-images.githubusercontent.com/9100169/7885195 …

Fix font sizing not applying to the site

---

content/data/unicorns.json
src/components/layout/layout.tsx
src/components/pic-title-header/pic-title-header.tsx
src/types/UnicornInfo.ts

One of the things that Thomas Hodges asked was for this LinkedIn to be added to his profile:
This PR adds that support

Added LinkedIn support to unicorns.json file

---

src/global.scss

This adds styling of `kbd` elements to match some default styling:

Adds styling to `kbd` elements

---

gatsby-config.js

Since we are a blog site, seeing a cached version of the homepage can lead to unintended side effects.
Switching from [`StaleWhileRevalidate`](https://developers.google.com/web/tools/workbox/modules/workbox-strategies#stale-while-revalidate) to [`NetworkFirst`](https://developers.google.com/web/tools/workbox/modules/workbox-strategies#network_first_network_falling_back_to_cache) will add a small blocking round-trip to fetch the latest version of the page. While this makes browsing slightly slower, if it doesn't match the version from the disk cache (if any), it will also download it from the server. If the network fails (e.g. offline) it will still fall back to the cached version from the service worker cache.
I'd like to test this in integration before making it into release since it …

Fix: Use NetworkFirst strategy for "non-cachable" page-data

---

src/components/privacy-error-boundary.tsx
src/pages/posts/[slug].tsx

I use a privacy browser plugin called "[Privacy Badger](https://privacybadger.org/)" from the EFF. It's fairly popular and it's a suggested Firefox plugin.
When changing the theme on UU where Disqus is loaded (like a blog post), it will crash the entire page and leave it blank and unresponsive due to it never actually being loaded and the React component trying to do some cleanup.
This PR adds in an intermediary step and handles the error that occurs during this step, replacing it with a message encouraging the user to take a look at #24
Admittedly, this acts as a bit of fuel to the #24 fire, but this is a short-term solution
Closes #287

fix: adds in privacy error detection and handling

---

content/blog/angular-components-control-value-accessor/index.md
content/blog/angular-templates-start-to-source/index.md
content/blog/how-to-upgrade-to-react-18/index.md
content/blog/master-react-unidirectional-data-flow/index.md
content/blog/python-list-comprehension-guide/index.md
content/blog/react-refs-complete-story/index.md
content/blog/rust-enums-matching-options-api/index.md
content/blog/understanding-the-dom/index.md
content/blog/web-components-101-lit-framework/index.md
src/global.scss
src/utils/markdown/MarkdownRenderer/media.tsx
src/utils/markdown/constants.ts

This PR (partially) fixes #299 by improving the default appearance of `<iframe>` elements on the site:
- Adds iframe border styling (matching the `<pre>` / code embed styles)
- Sets `width: 100%;` to expand the iframe to fill the post area horizontally, and `min-height: 500px;` vertically
- Refactors all iframes in posts to remove redundant inline styles
- Modifies the MarkdownRenderer to set `width="704" height="500"` (the default iframe size & container width) and `loading="lazy"` on all iframes
This change does not entirely remove the scroll bars from all iframes, but it should help to minimize the issue.
Notes:
- I have scrolled through all the modified posts to check for any wonky iframes, but it'd be good to have a second validation of that
- I've verified the new styles in the …

<iframe> CSS improvements

---

src/components/blog-post-layout/blog-post-layout.module.scss
src/global.scss
src/page-components/blog-post/suggested-articles/suggested-articles.module.scss

Right now, if you move between pages there's a few problems with our styling:
1) The blog post width isn't consistent and can lead to weird content shifts
2) The header doesn't align with the body contents
3) The sidebars don't have enough spacing when scrolled, but too much by default
This PR makes our styling more consistent between pages

feat: make styling more consistent

---

src/shiki.scss
src/tabs.scss

This PR improves the (currently unused) tab styling to go from this style:
To this one:

feat: improve tab styling

---

src/build-scripts/social-previews/twitter-large-card.test.tsx
src/build-scripts/social-previews/twitter-large-card.tsx

This attempts to improve upon the title splitting for accented text in articles' social media previews. Rather than picking an arbitrary point to split at, the proposed change searches for specific casing or punctuation to act as a delimiter. This makes its behavior more predictable and prevents the split from being placed in an undesirable location, such as the middle of a sentence or term.
The RegEx splits look for these details (in order of priority): colons/hyphens, comma-separated items, apostrophes, and lowercase words. Any matches directly at the start or end of the text will not be selected. If a title does not contain any of these, it will not be given an accent.
There are also two new test cases for this functionality; one for verifying the expected splitting behavior, and one …

Improved title splitting in social/preview image generation

---

content/data/languages.json
next.config.js
src/page-components/blog-post/blog-post.test.tsx
src/pages/about.tsx
src/pages/collections/[slug].tsx
src/pages/confirm.tsx
src/pages/index.tsx
src/pages/page/[pageNum].tsx
src/pages/posts/[...postInfo].tsx
src/pages/thanks.tsx
src/pages/unicorns/[...pageInfo].tsx

Currently, we're using our own implementation of i18n sub-routing which requires us to have dynamic paths for each page.
Here's a problem though: you can only have one dynamic path component per route, meaning that we could not port `about` or other pages with that method.
Because of this, we can utilize NextJS's default i18n routing logic

Next built in i18n

---

content/data/licenses.json
src/utils/fs/posts-and-collections-api.ts

At some point, this functionality was removed from the posts api - causing the site to generate an `<a aria-label="Post licensed with undefined">` instead of the correct license info for each post.
This PR fixes that behavior, and corrects one of the licenses' image paths.

Fix undefined license information in posts

---

src/utils/markdown/MarkdownRenderer/tabs.tsx

Currently when clicking between tabs in certain circumstances, it causes the following behavior of page jumping:
https://user-images.githubusercontent.com/9100169/175764283-88875ca2-a6f2-45b4-b1cc-fb961c6211a2.mp4
This is caused by a difference in content length between tabs
This PR looks to fix that.

fix: tabs no longer jump between large blocks of content

---

src/components/table-of-contents/table-of-contents.module.scss
src/components/table-of-contents/table-of-contents.tsx
src/constants/theme.ts
src/global.scss
src/pages/_document.tsx
src/styles/_text_styles.scss
src/utils/markdown/markdownToHtml.ts

- Offsets all heading depths within the table of contents by the minimum level used in a blog post
e.g. even if a post only uses `<h3>` and `<h4>`, the table of contents will still start at depth 1 instead of depth 3 (as it does now)
- Adds distinct `:hover` and `:focus` styles to the heading links
- Consolidates styling in the module SCSS (moved from global.scss)

Table of contents styling improvements

---

src/constants/theme.ts
src/global.scss

These changes focus on some existing styling behavior used in posts:
- The light mode background used for inline code has been improved to match the color scheme a bit better:
| Before | After |
| ------ | ----- |
| ![2022-07-12-133928_805x212_scrot](https://user-images.githubusercontent.com/13000407/178557492-a2b03cb9-65fe-4e04-b7d2-5d5aae628b7b.png) | ![2022-07-12-133920_791x209_scrot](https://user-images.githubusercontent.com/13000407/178557541-07c4b8bd-2c79-467b-ac5a-07082cd9894b.png) |
- Inline code styles are now also applied when used inside of `<li>` elements
- Table borders are no longer clipped by the edge of the containing element:
- `<hr>` elements have styling that matches the other border styles

Small improvements to markdown styling

---

content/blog/angular-extend-class/index.md

- The `takeUntil` operator must be last in an observable pipeline.

fix: the `takeUntil` operator must be last

---

src/page-components/about/about.astro
src/page-components/collections/collection-header-default.astro
src/page-components/post-list/post-list-header/post-list-header.astro
src/page-components/unicorns/profile-header/profile-header.astro
src/pages/404.astro
src/pages/collections/framework-field-guide/index.mdx
src/pages/confirm.astro
src/pages/thanks.astro

- Specifically defines the formats array on any astro `<Picture/>` tags
- Adds the `avif` format to picture tags that did not previously use it

add avif format to Astro images

---

src/styles/_text_styles.scss

This PR adds two fallback font faces based on the "Arial" and "Roboto" fonts, which should minimize layout shift when custom fonts are swapped (assuming they are available as local fonts on the device).
These fonts override the size and ascent of the local font to closely(ish) match the expected size of the custom font. This can still cause layout shift when the viewport size causes some lines to wrap differently, but the differences are much less common.
See also:
- https://deploy-preview-15--upbeat-shirley-608546.netlify.app/posts/high-performance-web-font-loading/
- https://simonhearne.com/2021/layout-shifts-webfonts/#reduce-layout-shift-with-f-mods

Use font-face "f-mods" to minimize layout shift

---

src/page-components/collections/framework-field-guide/segments/your-guide.module.scss

Previously, on Safari,  there would be a bug in Safari that caused a line on the right side of the Infinity symbol to appear.
**Before:** 
**After:**
This PR appears to side-step this issue without causing headaches on Chrome or Firefox

chore: fix the infinity symbol on your guide within Safari

---

src/page-components/blog-post/series/series-nav.astro

fix: previous and next blog icons render properly now

---

src/components/blog-post-layout/blog-post-layout.module.scss
src/components/table-of-contents/heading-intersection-observer-script.astro
src/components/table-of-contents/table-of-contents.astro
src/global.scss

This PR aims to improve the scrolling behavior of the post pages:
- The table of contents should scroll when the active elements are not in view (unless the user has `prefers-reduced-motion`)
- Prevents a horizontal scroll bar from appearing in specific viewport sizes
- Removes the small sidebar scroll movement at the top of the page due to container padding
(TBD whether this is actually an improvement)
- Changes opacity transition on right sidebar to one fade-in animation that applies to both
- Animates smooth scroll to heading on table of contents interaction (unless the user has `prefers-reduced-motion`)

Post scrolling behavior

---

src/styles/iframe-replacement.scss
src/styles/post-body.scss
src/utils/markdown/constants.ts
src/utils/markdown/rehype-unicorn-iframe-click-to-run.ts
src/utils/markdown/scripts/iframe-click-to-run.ts

This PR makes the iframe container sizing consistent with its replacement element, so that no page jumps occur when switching between them.

Fix iframe embed placeholder size

---

package-lock.json
package.json
src/styles/tabs.scss
src/utils/markdown/scripts/tabs.test.ts
src/utils/markdown/scripts/tabs.ts
src/utils/markdown/tabs/tabs.ts

This PR aims to automatically expand tab containers to the largest available tab content size when possible - to prevent moving around items on the page when a tab is selected. This should prevent most unintended scroll movement and possibly improve performance (by reducing the scope of layout recalculations when tabs are changed).
This is currently implemented using CSS `display: grid;` to overlap tab panels in the same grid cell, and switching from `hidden="true"` to `aria-hidden="true" visibility: hidden;` when hidden (so that hidden tabs still affect the layout).
However, these changes *will not apply* in the following conditions:
- Any tab has an approx. line height of >30 (determined during markdown rendering)
- The viewport is <=822px width (i.e. a mobile layout, where tab content …

Static tab heights

---

src/styles/iframe-replacement.scss
src/styles/post-body.scss
src/utils/markdown/constants.ts
src/utils/markdown/rehype-unicorn-iframe-click-to-run.ts
src/utils/markdown/scripts/iframe-click-to-run.ts

Temporarily reverts unicorn-utterances/unicorn-utterances#472 until it can be resubmitted with a fix - this broke the Framework Field Guide landing page because of page-specific CSS.

Revert "Fix iframe embed placeholder size"

---

src/components/layout/layout.astro
src/pages/404.astro
src/pages/[locale]/about.astro
src/pages/[locale]/posts/[postid].astro
src/pages/about.astro
src/pages/confirm.astro
src/pages/index.astro
src/pages/page/[page].astro
src/pages/posts/[postid].astro
src/pages/thanks.astro
src/pages/unicorns/[unicornid]/index.astro
src/pages/unicorns/[unicornid]/page/[page].astro

Fixes an issue where the `"listViewContent"` class is incorrectly applied to a localized blog post layout instead of the `"postViewContent"` class, causing a difference in page margins.
This class has been moved out of the `<Layout>` component and is now set per-layout at the top component level.

Fix inconsistent classes on translated posts

---

src/page-components/about/about.module.scss

See #490, images did not have a min width and would scale according to `display: flex` in mobile layouts.

Fix mobile responsiveness on contributors/about page

---

src/components/post-card-list/post-card-list.module.scss

Prevents the post grid columns from expanding when a significant length of text with no breakpoints is used as the post preview/description.

fix #492 - ensure equal width columns on the post grid

---

src/styles/post-body.scss

This PR introduces a number of changes to the table styling:
- Reduces padding & line height on table cells
- Wraps inline code blocks within table cells
- Eliminates horizontal scrolling on table containers
- Fixes the cut off table borders bug (caused by the overflow property)
- Adds sticky table headers
Comparison: (on https://unicorn-utterances.com/posts/ultimate-windows-development-environment-guide)
| Existing version | Changes in this PR |
|----------------------|------------------|
| ![2023-03-05-021858_848x604_scrot](https://user-images.githubusercontent.com/13000407/222947645-0a64b5a4-e3e0-4dc8-a38c-010162f7b951.png) | ![2023-03-05-022857_824x379_scrot](https://user-images.githubusercontent.com/13000407/222947689-b68c20cd-41f2-4fb3-b668-f350558b0bbb.png) |

Sticky table headers, smaller line-height, & better wrapping on tables

---

src/utils/markdown/rehype-astro-image-md.ts

This PR excludes .gif images from image optimization to avoid broken picture tags.
There is currently only one post using gifs which exhibits the loading issue when the `medium-zoom` overlay is opened: https://unicorn-utterances.com/posts/async-pipe-is-not-pure

Exclude gifs from image optimization

---

src/components/table-of-contents/heading-intersection-observer-script.astro

Fixes a smooth scrolling bug making the table of contents difficult to use on some pages.
When deciding whether the page should smooth scroll to a heading, the page first checks that both the current and clicked heading links are visible within the ToC container.
This prevents the table of contents from updating mid-scroll and breaking the scroll transition.

Prevent table of contents smooth scrolling when clicked link is out of view

---

src/utils/markdown/get-picture-hack.ts
src/utils/markdown/rehype-astro-image-md.ts

I noticed in a draft of FFG, that images won't load properly in some instances:
Despite being valid MD:
This PR fixes this issue, which seems to be caused by a weird `width` caused by some odd math calculations:
```
/_image?f=avif&w=632.4705882352941&h=768&ar=0.8235294117647058&href=%2Fcontent%2Fblog%2Fffg-fundamentals-intro-to-components%2Fsidebar.png 632.4705882352941w
```
This PR also:
- Updates our `sharp` image to use `squoosh`
- Adds `AVIF` support to in-MD images
- Fixes medium-image-zoom

Fix image loading at weird sizes

---

src/styles/tabs.scss
src/utils/markdown/tabs/tabs.tsx

This PR updates tabs to look like this:
Per the mockups.
It temporarily removes the `small-tabs` logic, as there's no fixed content width to dynamically calculate from.
Preview: https://unicorn-utterances-git-uwu-tabs-refresh-oceanbit.vercel.app/posts/angular-extend-class

[UWU] Tabs Styling Updates

---

src/views/blog-post/table-of-contents/table-of-contents.module.scss

- Specifies the vertical padding on nested ToC items (fixes the border spacing issue in #563)
- Uses `:has(:focus-visible)` in place of `:focus-within` to avoid using the extended line on focus
- Adds `:not(:active)` to conditions for showing the border line

[UwU] Fix ToC border behavior with line wrapping

---

public/icons/arrow.svg
public/icons/dot.svg
src/views/blog-post/table-of-contents/table-of-contents.module.scss

Fixes #572
This PR migrates away from an SVG background to using an SVG mask in order to apply variable colors for the TOC icons

[UWU] Fix TOC Icon Colors

---

src/styles/variables/icons.scss

This PR changes the icon tokens to be `rem` based rather than `px` based, based on a convo with @PrattiDev, which he had with @fennifith

[UwU] Dynamic icon size

---

src/styles/variables/fonts.scss

@PrattiDev noticed that the large button text style tokens were flipped for desktop and mobile. This PR fixes that

[UwU] Large button text fix

---

src/components/post-card/post-card.module.scss
src/components/post-card/post-card.tsx
src/global.scss
src/styles/container.scss
src/styles/grid.scss
src/styles/markdown/blockquote.scss
src/styles/markdown/embed.scss
src/styles/markdown/hints.scss
src/styles/markdown/lists.scss
src/styles/markdown/table.scss
src/styles/markdown/tabs.scss
src/styles/markdown/tooltips.scss
src/styles/text-styles.scss
src/views/blog-post/post-title-header/post-title-header.astro
src/views/collections/collection-page.module.scss
src/views/unicorn/unicorn-layout/unicorn-layout.module.scss

- Remove `1fr 1fr` row template, which was forcing both the metadata & bio rows to be an equal height
- Add `align-self: center` to items on the metadata row for vertical alignment
- Fixed scaling bug with a font style incorrectly applied to `:root`
- Replace spacing styles with `var(--site-spacing)` to match specs

[UwU] Misc. spacing, scaling, & centering fixes

---

src/components/pagination/pagination.module.scss
src/components/pagination/pagination.tsx
src/components/pagination/types.ts

- Changes the pagination item count to show the correct number of items on desktop
- Adds a mobile breakpoint that hides some of the items on mobile
(specifically, leaves only the 4 closest pages, plus the "more", "next", and "previous" buttons)

[UwU] Pagination mobile breakpoint

---

src/styles/markdown/file-list.scss
src/utils/markdown/file-tree/file-list.tsx
src/utils/markdown/file-tree/rehype-file-tree.ts

This PR doesn't include styling yet, but migrates the file list component to use JSX for the markdown transform and provides a nicer temporary styling:
> Shown with highlight and comments, which are not really in the blog post

[UwU] Convert file list Markdown transform to JSX

---

src/views/blog-post/article-nav/article-nav.module.scss

Reorders the next/previous article nav buttons on mobile, so that "next" appears above the "previous" button.

[UwU] Fix article nav order on mobile

---

src/components/button/button.tsx

Using `createElement` causes SUPER unexpected issues due to an inconsistent key treating the component as if it were an entirely different component. This makes focus move in strange ways (to/from the element) which doesn't impact our code.... Until it does. I've lost hours debugging this.
Additionally, our code allows for any `a` code to be used on `button` tag `Button`s and vice-versa.
Lastly, `ref` wasn't forwarding properly.
This PR fixes all three.

[UwU] Button fixes

---

.eslintrc.cjs
astro.config.ts
package-lock.json
package.json
src/components/input/input.module.scss
src/components/pagination/pagination-popover.module.scss
src/components/pagination/pagination-popover.tsx
src/components/pagination/pagination.module.scss
src/styles/button.scss

> This PR builds on top of #618, merge that first.
This PR replaces Floating UI with React Aria, in expectations of using that package more for other UI elements.
It's about the same bundle size with my testing, and has a known reputation of handling A11Y better.
I had to migrate to using `aria-disabled` rather than `disabled` prop for the pagination increment/decrement buttons. Without doing so, the buttons lose focus which causes the focus manager to break and cause bad UX.

[UwU] Migration pagination to use React Aria

---

build-scripts/social-previews/shared-post-preview-png.ts
src/utils/get-all-posts.ts
src/utils/markdown/file-tree/rehype-file-tree.ts
src/utils/markdown/rehype-astro-image-md.ts
src/utils/markdown/rehype-excerpt.ts
src/utils/markdown/rehype-unicorn-get-suggested-posts.ts
src/utils/markdown/rehype-unicorn-populate-post.ts
src/utils/markdown/rehype-word-count.ts
src/utils/markdown/types.ts

This PR makes the remark and rehype typings more strict in UWU to prep for a eslint dep upgrade that strongly dislikes `any` usage whenever possible.

[UwU] Make rehype and remark plugins more type strict

---

.prettierrc

This PR fixes issues with the Prettier 3 migration that stopped it from running during the commit phase. I missed this originally, but is now fixed
https://prettier.io/blog/2023/07/05/3.0.0.html#plugin-search-feature-has-been-removed-14759httpsgithubcomprettierprettierpull14759-by-fiskerhttpsgithubcomfisker

[UwU] Fix prettier

---

src/components/collection-card/collection-card.astro
src/components/collection-card/collection-card.module.scss

- Prevents collection card content from extending beyond the flex container size
- Adds `text-overflow: ellipsis` to prevent individual words overflowing past the container

[UwU] Ellipsize text on collection card overflow

---

src/components/post-card/post-card-grid.tsx
src/views/explore/homepage.astro
src/views/explore/homepage.module.scss
src/views/explore/page.astro
src/views/search/search-page.module.scss
src/views/search/search-page.tsx
src/views/unicorn/unicorn-page.astro

This PR replaces duplicate `aria-label`s with `aria-labelledby` and linking to a relevant header.
In addition, we're also replacing non-lists with lists when expected for collections

[UwU] Improve list/collections A11Y

---

src/views/search/components/filter-dialog.module.scss
src/views/search/search-page.tsx

Fixed #653 by replacing `overflow: hidden` with `overflow: clip` on the affected containers. This prevents their content from being programmatically scrolled whenever a React input is interacted with.

[UwU] Prevent search filters from teleporting off the page

---

content/site/about-us.es.md
content/site/about-us.fr.md
content/site/about-us.md
content/site/about-us.pt.md
src/components/input/input.module.scss
src/components/post-card/post-card.module.scss
src/styles/post-body.scss
src/styles/text-styles.scss
src/views/about/about.astro
src/views/blog-post/post-title-header/post-title-header.astro
src/views/collections/collection-chapter.astro
src/views/collections/collection-page.astro

The modular CSS appears to have a higher specificity in prod than in dev mode, resulting in some unreliable behavior. This fix hopefully prevents any more text-styles related issues involving this.
- All of the text-styles classes now use a `:where()` selector to reduce their specificity
- Any default text styling for elements is removed.
* i.e. no more `p, .text-style-body-large { ...`. Any `<p>` or `<h#>` element will need to specify which text style class to use.
* This prevents a `<p class="text-style-body-small">` from being affected by the `text-style-body-large` styling (since the two selectors would conflict if placed inside a `:where()` selector)
* Selectors in `.post-body` now `@extend` the respective text styles to apply them to post contents
- The `margin: 0;` causing input …

[UwU] Fix mailing list input layout shift

---

src/components/checkbox-box/checkbox-box.module.scss

Adds `user-select: none;` to the checkbox icon container to prevent it from being selected. This might've been causing strange onclick behavior (causing double-clicks) when nodes inside the selection were rerendered.

[UwU] Fix filter checkbox text selection causing strange behavior

---

src/components/button-radio-group/button-radio-group.tsx
src/components/select/select.tsx
src/views/search/components/filter-display.tsx
src/views/search/components/filter-sidebar.tsx
src/views/search/components/search-topbar.tsx
src/views/search/search-page.tsx

This PR allows us to remove the default sort type (and allow the user to unselect one once they active one) so that the user can see the server's default sort order (important so that we can order the search results by most relevant to the user)
Notable screenshots:
Closes #661

[UwU] Remove default sort type

---

src/views/search/components/filter-sidebar.module.scss

Ensures that the sidebar container has sufficient padding to not clip focus state outlines.

[UwU] Avoid clipping focus states in the search sidebar

---

src/components/collection-card/collection-card.module.scss
src/components/collection-card/collection-card.tsx
src/components/input/input.tsx
src/components/pagination/pagination-popover.tsx
src/components/post-card/post-card-grid.tsx
src/components/post-card/post-card.tsx
src/components/search-section/search-section.astro
src/pages/[...locale]/collections/[slug].astro
src/views/collections/collection-page.astro
src/views/collections/collection-page.module.scss
src/views/explore/homepage.astro
src/views/search/components/filter-dialog.tsx
src/views/search/components/search-topbar.tsx
src/views/search/search-page.spec.tsx

Fixes a few things identified by lighthouse:
- Collection cards (on the homepage) now use properly optimized `<picture>` tags
- Redundant alt text on the collection card profile pictures is removed (the image is directly adjacent to the author name)
- Set expanded collection card images to `loading="eager"` when above-the-fold
- Added missing `aria-labels` to a bunch of buttons
- Use displayed cover image aspect ratio instead of the source image size (otherwise it gets stretched by the browser)

[UwU] Assorted lighthouse fixes

---

src/utils/href-container-script.ts
src/views/blog-post/article-nav/article-nav.module.scss
src/views/blog-post/article-nav/article-nav.tsx

- Removes the obsolete `data-navigation-path=` attribute, uses `getHrefContainerProps()` to get the correct props for nav items
- Fixes a specificity issue causing the previous/next article buttons to be placed on different grid rows in the desktop layout:
| Current Behavior | Expected|
|------|-------|
| ![2023-09-09-111242_889x696_scrot](https://github.com/unicorn-utterances/unicorn-utterances/assets/13000407/fc92e834-81c9-478b-b9f2-cd8c1c54329e) | ![2023-09-09-111209_855x578_scrot](https://github.com/unicorn-utterances/unicorn-utterances/assets/13000407/d353dac2-037a-4d38-93a8-e37bafbb6f93) |

[UwU] Fix article nav

---

src/views/blog-post/post-title-header/post-title-header.astro
src/views/blog-post/post-title-header/post-title-header.module.scss

- Fixes icons shrinking at small viewports (due to `flex-shrink`)
- Changes flex alignment to `top` instead of `center` (so the icons stay aligned with the first line when wrapping)
- Splits "last updated" text onto a separate line on mobile, to match mockups
| Before | After |
|----|----|
| ![2023-09-09-121842_221x370_scrot](https://github.com/unicorn-utterances/unicorn-utterances/assets/13000407/cadf413f-6ec3-4f9f-af84-d3817aac4b52) | ![2023-09-09-115247_243x376_scrot](https://github.com/unicorn-utterances/unicorn-utterances/assets/13000407/6cd2dc1b-9bc9-45e3-a4de-165dacdbd39d) |

[UwU] Fix wrapping behavior of article header metadata

---

src/components/input/input.module.scss
src/tokens/_breakpoints.scss
src/views/collections/framework-field-guide/tokens/_utils.scss
src/views/search/components/filter-dialog.tsx
src/views/search/components/filter-display.tsx
src/views/search/components/filter-section-item.module.scss
src/views/search/components/filter-section-item.tsx
src/views/search/components/filter-section.module.scss
src/views/search/components/filter-sidebar-props.scss
src/views/search/components/filter-sidebar.module.scss
src/views/search/components/filter-sidebar.tsx
src/views/search/search-page.module.scss
src/views/search/search-page.tsx

- Sets the `max-width` of the search page layout to match the "xl" page size.
- Adds `opacity: 0;` to make the sidebar invisible when hidden
- Changes the layout to `display: grid` in order to perform the sidebar transition when hidden
* This fixes the issue where the page would briefly show the sidebar and then perform the hidden transition when the page first loads
- Adds hover/focus styling to filter elements:
* #645 
* #643
- Adds styling to override the input autofill color/background
- Fixes breakpoint comparisons to use separate ranges; so that usage does not overlap at breakpoint values
* `until(x)` is now `[0, x]` (inclusive) or `width <= x`
* `from(x)` is now `[x+1, inf]` or `width > x`
- Increases the filter dialog breakpoint by 100px to prevent overflow
* #655

[UwU] Search page styling changes

---

src/utils/markdown/constants.ts
src/utils/markdown/iframes/rehype-transform.ts

Fixes #678 by ensuring iframes have a minimum height of `300px`

[UwU] Set a minimum height for iframe embeds

---

src/global.scss
src/styles/post-body.scss
src/utils/markdown/rehype-astro-image-md.ts

- Uses the `width` or `height` attributes as the image size, if present
* If only one is provided, the other is inferred from the aspect ratio
* If both are present, `height` takes precedence, and the width is inferred
- Sets both `height=` and `width=` attributes in the output html
- Adds a `z-index: 999;` for the medium-zoom overlay to prevent it from colliding with the navbar

[UwU] Use width/height attributes on `<img>` tags when provided

---

content/blog/intro-to-web-accessibility/index.md
content/blog/web-components-101-framework-comparison/index.md
content/blog/web-components-101-lit-framework/index.md

Fixes various posts using formatting that resulted in styling issues:
- [Intro to Web Accessibility](https://unicorn-utterances-git-uwu-inline-styling-oceanbit.vercel.app/posts/intro-to-web-accessibility) (HTML table missing a `<thead>` / `<tbody>`)
- [Web Components 101: Framework Comparison](https://unicorn-utterances-git-uwu-inline-styling-oceanbit.vercel.app/posts/web-components-101-framework-comparison) (HTML table missing a `<thead>` / `<tbody>`)
- [Web Components 101: Lit Framework](https://unicorn-utterances-git-uwu-inline-styling-oceanbit.vercel.app/posts/web-components-101-lit-framework) (unescaped inline code backticks)

Fix table & inline code formatting

---

src/styles/markdown/hints.scss
src/styles/post-body.scss
src/utils/markdown/file-tree/file-list.tsx
src/utils/markdown/file-tree/rehype-file-tree.ts

Adds the inline markdown styling for `<code>` and `<kbd>` elements from #676

[UwU] Inline <code> / <kbd> styling

---

src/styles/shiki.scss

Fixes #690 
- Sets the code block line counter psuedoelement to `position: absolute;`, and offsets the code itself using `padding:`
* This fixes the tab alignment so that it is not affected by the width/margin of the line numbers
- Changes the default tab size to `tab-size: 4;`
- Sets the line `min-height:` to the current line-height value (`1.7em`)
* This prevents now-empty line divs from having a smaller height than other lines with code.

Prevent code block line counters from affecting tab alignment

---

src/components/seo/shared.ts
src/pages/404.astro
src/pages/collections/[slug].astro
src/pages/collections/framework-field-guide/index.astro
src/pages/confirm.astro
src/pages/index.astro
src/pages/page/[page].astro
src/pages/thanks.astro
src/pages/unicorns/[unicornid]/index.astro
src/pages/unicorns/[unicornid]/page/[page].astro

This should fix some pretty big SEO and scraping issues (IE: Facebook/LinkedIn's image preview tag) with our pages

chore: add missing pathName to pages

---

src/components/select/select.module.scss

Attempt to fix the select filter boxes retaining their focus background after being hovered over.

[UwU] Use :focus-visible for filter select focus state

---

src/styles/markdown/tabs.scss

Applies the tab content margin to headings as well as other text content within tabs, so that they're aligned properly.
Prevents issues like this:

[UwU] Add heading selectors for text spacing within tab contents

---

src/utils/markdown/iframes/iframe-placeholder.tsx
src/utils/markdown/iframes/iframe-script.ts
src/utils/markdown/iframes/rehype-transform.ts

When adding an iframe in a blog post, we might want to have flags akin to this:
```html
<iframe src="https://example.com" sandbox="allow-modals allow-forms allow-popups allow-scripts allow-same-origin" allow="cross-origin-isolated"></iframe>
```
But today we do not preserve the `sandbox` or `allow` flag. This PR fixes that behavior.

[UwU] Preserve iframe flags

---

content/blog/test-edge-cases/index.md
src/styles/markdown/lists.scss

- Removes the bowtie styling from unordered lists
- Inherits the `<p>` font styling for list item content by default
(this fixes empty `<li>text content</li>` having a different font size from `<li><p>text content</p></li>`)
- Removes the styling preventing nested lists from adding top/bottom margins
- Applies styling to `<ol>` ordered lists as well as unordered lists

[UwU] List changes

---

src/utils/markdown/rehype-header-text.ts
src/views/blog-post/table-of-contents/heading-intersection-observer-script.astro

- Changes the page URL to include the heading ID when its ToC entry is clicked
- Sets heading `scrollIntoView()` call to use `block: "center"`
- (prevents headings from being hidden behind the fixed nav)
- Fixes duplicate table of contents entries after reloading a post in dev mode

[UwU] Fix table of contents links

---

src/styles/markdown/hints.scss

- Fixes styling issues from `<details>` invisibly changing `box-sizing` to `content-box` (?)
- Sets the `<details>` to 100% width when it `:has()` a codeblock, embed, or file tree list.

[UwU] Fix hint width & box-sizing styles

---

src/views/base/navigation/header.module.scss

- Sets `flex-shrink: 0;` on buttons in the nav header to fix #703

[UwU] Fix non-circular nav buttons in tablet mode

---

src/components/button/button.tsx
src/components/hero/hero.astro
src/components/post-card/post-card.tsx
src/views/base/navigation/header.astro
src/views/blog-post/blog-post.astro
src/views/blog-post/post-title-header/post-title-header.astro

After speaking with @evelynhathaway and @colabottles, it became clear that we should migrate to roughly this markup:
```html
<body>
<header>
<nav id="1"></nav>
</header>
<main>
<section id="2"></section>
<section id="3"></section>
<section id="4"></section>
<section id="5"></section>
</main>
<footer>
Any copyright info, links, social media icons, etc. can go here.
</footer>
</body>
```
For this homepage outline:
Content that changes on a per-page basis should use a `section` rather than a `header` and our header nav should have both: `header` (which has `role="banner"`) and `nav`
In addition, this PR fixes #720, fixes #721

[UwU] More A11Y Fixes

---

astro.config.ts
content/blog/example/index.md
content/data/achievements.ts
src/components/seo/seo.astro
src/components/seo/shared.ts
src/pages/[...locale]/posts/[postid].astro
src/pages/rss.xml.ts
src/types/PostInfo.ts
src/utils/api.ts
src/utils/get-all-posts.ts

Fixes #699 - Adds an "example post" that should be excluded from the rest of the site.
- Any `utils/api` queries (and `getAllExtendedPosts`) exclude posts with the `noindex: true` frontmatter.
* This should result in them being excluded from all post lists and the generated search index
- `noindex` posts are filtered from the RSS feed
- A `<meta name="robots" content="noindex, nofollow" />` is added to the header of any noindex post page.
According to Google's [developer docs](https://developers.google.com/search/docs/crawling-indexing/block-indexing), the page should still be accessible from `robots.txt`; i.e. adding this tag alone should be sufficient.
TODO: not sure if anything needs to be done to the sitemap

[UwU] Add noindex frontmatter property for test posts

---

src/components/post-card/post-card.module.scss
src/components/post-card/post-card.tsx
src/views/blog-post/post-title-header/post-title-header.module.scss

- Prevents post card metadata icons from shrinking with `flex-shrink`
- Fixes wrapping behavior / icon alignment to match post header
- Fixes the post header `align-items:` properties not having a valid value (`align-items: top` does not exist! oops.)

[UwU] Fix post metadata wrapping behavior

---

content/blog/minecraft-data-packs-cmd-syntax/index.md
content/blog/minecraft-data-packs-introduction/index.md
content/blog/minecraft-data-packs-scoreboards/index.md

As per https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom; the previous links are no longer maintained.

Update MC wiki links to point to "minecraft.wiki"

---

src/global.scss

This fixes situations where scrollbars are displayed on a container with a different background color and look out of place:
Result:
Tested on Chrome & Firefox; might need testing on Safari.

[UwU] Set scrollbar track background to transparent

---

content/data/i18n/en.json
src/components/related-posts/related-posts.astro
src/components/search-section/search-section.astro
src/views/base/navigation/dark-light-button/dark-light-button.astro
src/views/search/components/filter-section-item.tsx
src/views/search/components/filter-section.tsx
src/views/search/search-page.tsx

Fixes most of the smaller a11y issues that could fit in a single PR:
- Clarify the "toggle dark mode" button label (#735)
- Fix `<li>` elements missing from the related posts list (#737)
- Adds the "Post tags" label missing from the search section tag list (#740)
- Move focus to the search filter heading button when the "Clear" button is pressed (#742)
- Describe search filter post counts with an aria-label (#743)
- Use aria-live `polite` instead of `assertive` on the search status message (#744)

[UwU] Various accessibility fixes

---

src/styles/shiki.scss
src/utils/markdown/index.ts
src/utils/markdown/twoslash-tabindex/rehype-transform.ts
src/utils/markdown/twoslash-tabindex/twoslash-tabindex-script.ts
src/views/blog-post/blog-post.astro

- Removes the `opacity: 0.5;` styling for non-highlighted parts of code blocks
* Instead, highlighted sections are bold + bordered
* #739
- Fixes other code block styling issues (highlighted lines not expanding to the full code block width when scrollable)
- #738
* Adds a rehype transform to add `tabindex="0"` on any `div.code-container`
* Adds a script that sets `tabindex="0"` only if the `div.code-container` is horizontally scrollable

[UwU] Fix code block contrast & tabindex issues

---

src/styles/button.scss
src/views/search/components/filter-sidebar.module.scss

Button focus states were previously implemented with `box-shadow`, which did not match the specs. Implementing with `outline-offset` separates the outline from the button background to maintain contrast.
- Fixes #736 
- Doubles the negative sidebar margin/padding on the search page to accommodate the increased outline size

[UwU] Fix button outline styling to match spec

---

src/components/select/select.tsx

- Removes `id`, `aria-labelledby`, and `aria-describedby` attributes from the props returned from `react-aria` within its `<Popover>` component
#741

[UwU] Fix invalid <Select> popover IDs

---

content/blog/js-classes-without-keyword/index.md

docs: fix typo on JS classes article

---

src/components/select/select.module.scss

- Adds the specified border to the sort dropdown: #767 
- Removes an unused `.selectDropdown` class

[UwU] Fix select border

---

content/data/i18n/en.json
src/utils/translations.ts
src/views/base/navigation/dark-light-button/dark-light-button.astro
src/views/base/navigation/dark-light-button/theme-toggle.ts
src/views/base/navigation/header.astro
src/views/base/navigation/header.module.scss

- Removes "Join our Discord" header link on the homepage
- Removes "About us" header link on the homepage (duplicated by "Learn more")
- Fixes the `--header_end-items_max-width` token to align the header items with the page content
- Adds a large theme toggle variant (with "Switch theme" text) on the homepage to make up for the lack of space

[UwU] Remove duplicate homepage links

---

src/components/search-section/search-section.astro
src/views/base/navigation/header.astro

These placeholders were reading as duplicate labels, this PR solves this:
https://github.com/unicorn-utterances/unicorn-utterances/issues/781

[UwU] Remove search placeholder

---

src/views/unicorn/unicorn-page.astro

- Sets the button's inner `<span>` text instead of the button `innerText` to avoid overwriting its `<span>` element. Fixes #797

[UwU] Fix replaced achievement button span

---

src/components/pagination/pagination.tsx
src/views/explore/page.astro

- Changes the `<PaginationMenuWrapper>` behavior to return an `<li hidden>` in its default case so that it hydrates in the correct order
- Specifies prop keys to avoid generating a huge JSON object for the pagination in the HTML
Fixes #807

[UwU] Fix pagination popup hydration order

---

src/views/blog-post/blog-post-layout/blog-post-layout.module.scss
src/views/blog-post/blog-post.astro
src/views/blog-post/post-title-header/post-title-header.astro
src/views/blog-post/series/series-toc.astro

- Fixes the series title heading order (`h2` -> `h3`)
- Prevents it from acting as a "copy link" heading, which overrode the `<a>` click behavior:

[UwU] Fix series heading behaving as a "copy link" target

---

src/global.scss
src/styles/post-body.scss

Replaces `scroll-padding-top` with a `scroll-margin-top` style on all heading elements.
Fixes #845

Fix header search bar focus causing the page to scroll upwards

---

src/styles/shiki.scss

Fixes CSS for code blocks missing the top/bottom border styling when at the start or end of a code block.

Fix highlight border missing when at the last/first index in a codeblock

---

src/utils/markdown/rehype-header-text.ts

This fixes #1016, which caused duplicate ToC headings to be created for tab containers. Headings are no longer counted if they are inside tab contents or inside a `<details>` element.

Fix headings from tab containers appearing in table of contents

---

src/styles/post-body.scss
src/utils/markdown/rehype-astro-image-md.ts

- Adds a `display: block; on picture tags to fix #1017 
- Fixes the image max_width (used for image compression) to match the max page content size (which is now 896px)

Fix picture images not sizing correctly in tab containers

---

content/blog/example/index.md
src/views/base/scripts/heading-link-script.astro
src/views/base/scripts/heading-link.module.scss

Fixes #868 - and also prevents the "Copy link" underline/prompt from appearing when the link is hovered, for clarity about what action clicking will perform
https://unicorn-utterances-git-fix-links-inside-headings-oceanbit.vercel.app/posts/example_noindex#Heading-with-a-link-inside-of-it

Prevent "copy link" styling/behavior when a link is used inside a heading

---

src/utils/href-container-script.ts
src/views/collections/collection-chapter.astro

Fixes the "? Coming soon..." link on collections opening a `/undefined` link due to its onclick event handler.
https://unicorn-utterances.com/collections/minecraft-data-packs

Fix collection chapter onclick opening an undefined link

---

.github/workflows/test.yml

This changes our CI pipelines such that:
- It only runs on pushes to `main`
- It runs on any PRs to `main`
- Adds a concurrency mode to avoid high utilization of CI
- Updates our actions
- Uses Node from `.nvmrc`

chore: update CI pipeline

---

src/styles/post-body.scss

Closes [#972](https://github.com/unicorn-utterances/unicorn-utterances/issues/972)
On iOS devices (Safari, Chrome) code font-size inside markdown files was bigger.
Before: 
After:

Fix(#972): different code font-size on iOS

---

src/global.scss

[`scrollbar-gutter: stable`](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter) reserves space for the scrollbar even if the page content is not scrollable.
AFAIK this really only has an effect on Chromium browsers - Safari doesn't support it, and Firefox has an overlay / zero-width scrollbar for which this has no effect.
However, this does prevent the search page content from jumping around before/after the search results have loaded.

Add `scrollbar-gutter: stable` to prevent layout shift

---

src/styles/markdown/tabs.scss
src/utils/markdown/tabs/rehype-transform.ts

Fixes #1053 
This makes a few changes to tabbed containers:
- When reserving space for tabs, the tab background now extends to the full height of the container
- Added back `overflow-anchor: none;`, which was missing from the tab containers
* This prevents page jumps when the selected tab is changed by forcing the browser to pick a scroll anchor outside
of the tab content
- Increased the line count that an image adds to the estimate
* Each image is now equivalent to 20 lines, where the space-reservation limit is 30 lines - so a tab with multiple images cannot reserve space (this prevents the empty space mentioned in the issue)

Various fixes for tabs

---

src/styles/markdown/tabs.scss

This reverts commit 9e9a714739177bcf22ff262c3d0850d8dac75322.
Applying this specifically to the tab panel still allows the browser to choose the tabs element as a scroll anchor, which can apparently still cause scroll jumps.

Revert "apply overflow-anchor only to the tab panels"

---

content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-accessing-children/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-component-reference/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-dependency-injection/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-derived-values/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-directives/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-dynamic-html/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-element-reference/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-error-handling/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-intro-to-components/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-passing-children/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-portals/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-shared-component-logic/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-side-effects/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-transparent-elements/index.md

This PR moves away from `typescript` and towards `ts-angular` syntax highlighting for the template in Angular code samples for FFG

[Markdown Deastroify] Move FFG Angular Syntax to Fix Highlighting Issues

---

content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-preface/index.md

This PR fix the incorrect links to Remix and Vercel in the Preface

docs: fix Remix and Vercel links in FFG's preface

---

src/views/blog-post/blog-post.astro

Fixes the issue in #1072, where you'd land on a 404 when clicking to view the post on GitHub.
The link was not updated from when the content directory was restructured. Now we can just use the post path to construct the url.

Fix GitHub link on posts

---

content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-element-reference/index.md

Fix the double backtick typo and improve sentence flow (IMHO) by removing `the` before `ngIf`.

Fix double backtick typo

---

src/components/button/button.tsx
src/components/pagination/pagination-popover.tsx
src/components/select/select.module.scss
src/components/select/select.tsx
src/hooks/useReactAriaScrollGutterHack.ts
src/styles/button.scss

- Separates the scroll gutter hack into a `useReactAriaScrollGutterHack` hook
- Adds `useFocusRing()` to the `<Select>` component buttons and option elements to conditionally apply the focus styling

Fix layout shift & focus bug on search filter dropdowns

---

src/components/post-card/post-card.tsx

Fixes the word count being placed in post cards without `.toLocaleString()` (which adds the comma in its other locations)

Fix missing commas in word count on post card

---

content/crutchcorn/posts/how-computers-speak/index.md

This PR includes just a few small changes to [How Computers Speak](https://unicorn-utterances.com/posts/how-computers-speak), fixing various typos.

Fix: Minor changes and typo removal in "How Computers Speak"

---

build-scripts/epubs/epub.css

fix: styling for inline code blocks should wrap for epubs

---

src/views/join-us/contributor-card.astro
src/views/join-us/contributor-card.module.scss
src/views/join-us/get-involved-header.astro
src/views/join-us/get-involved-header.module.scss
src/views/join-us/get-involved-header.ts
src/views/join-us/welcome-to-everyone.module.scss

Ports the contributors header to a canvas implementation - this significantly reduces lag on mobile devices when the bubbles are animating.
Also makes a few behavior changes:
- Uses `getPicture` to obtain sized image URLs from Vercel (passed in through `data-unicorns` on the canvas)
- Makes all animation timestamp-dependent to avoid behavior differences due to refresh rate
- Uses [passive event listeners](https://developer.chrome.com/docs/lighthouse/best-practices/uses-passive-event-listeners/) that won't block scrolling on mobile
- Prevents vertical drags (i.e. scrolling on mobile) from moving the canvas

New "Join Us" page - Canvas implementation

---

src/components/hero/hero.module.scss

This makes it so the hero buttons display in a row rather than a column after the 1280px requirement is met. Previously this only happened when the display was larger than 1920px.

Hero buttons fix for desktopSmall

---

src/styles/markdown/in-content-ads.scss

Makes it so the inner background does not overlap the sticker illustration

Open Collective ad `z-index` fix. 

---

FEATURES.md
astro.config.ts
src/pages/[...locale]/posts/[postid].astro
src/pages/robots.txt.ts
src/types/CollectionInfo.ts
src/types/PostInfo.ts
src/utils/api.ts
src/views/blog-post/series/series-toc.astro

This PR:
- Adds some new frontmatter properties on posts and collections to attribute differently versioned (but otherwise similar contents of) posts and collections to one another
- Documents those new properties
- Adds support for `noindex` collections
- Makes it so that URLs don't add `_noindex` to the slug of `noindex` posts
- Add `noindex` support to `robots.txt` for prod

Improve `noindex` usage for collections, posts, robots.txt

---

src/utils/data.ts

The NPM `junk` folder seemingly wasn't filtering out `.idea` or `.vscode` files anymore, so I added them to our filters.
This makes it so that when one opens a subfolder in an IDE it doesn't break dev mode.

fix: devmode now works with opening idea and vscode files

---

src/components/checkbox-box/checkbox-box.module.scss
src/components/input/input.module.scss
src/components/pagination/pagination-popover.module.scss
src/components/related-posts/related-posts.module.scss
src/components/search-section/search-section.module.scss
src/styles/container.scss
src/styles/markdown/base.scss
src/styles/markdown/codeblock.scss
src/styles/markdown/lists.scss
src/styles/text-styles.scss
src/styles/utilities.scss
src/views/base/navigation/rebrand-announcement-banner/rebrand-announcement-banner.module.scss

The focus outlines on hyperlinks aren't currently working when tab-focused - the SCSS functions aren't being recognized and are ending up in the CSS output:
```css
.post-body a:focus-visible:not([class]) {
outline: pxToRem(3.5) solid var(--focus-outline_primary);
outline-offset: pxToRem(1.5);
border-radius: calc(var(--border-width_focus)/2);
}
```
This PR replaces every `@use "src/tokens/index";` with `@use "src/tokens/index" as *;`. Most of these instances don't use any functions/variables from the import, but should help avoid future issues.

Fix invalid CSS on hyperlink focus outline

---

content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-intro-to-components/index.md

As discussed on discord, the example in the Rendering the App section should refer to File.vue instead of App.vue.
https://discord.com/channels/609050358949347368/1094715906577403905/1310404508043444295

Refer to File.vue in Vue example

---

src/views/blog-post/blog-post-layout/blog-post-layout.module.scss
src/views/blog-post/series/series-toc.astro
src/views/blog-post/series/series-toc.module.scss
src/views/collections/framework-field-guide-fundamentals/components/collection-table-of-contents-fundamentals.astro
src/views/collections/framework-field-guide-fundamentals/components/collection-table-of-contents-fundamentals.module.scss
src/views/person/person-page.astro

One of the items seemingly not mentioned in the v5 migration guide is that `data-some-attr={false}` will now stringify `false` as `'false'` rather than remove it entirely.
This caused a few bugs in our system that are now fixed

Astro v5 Fixes

---

src/views/base/navigation/header.astro
src/views/base/navigation/header.module.scss

Fixed clipping of the CSS icon in the banner by making the header transparent until a scroll is detected. Removed the transition duration as a 1px divider isn't gonna make or break anything.
Couldn't find any conflicting pages with this change.
Also fixed - in my particular way - the doubled theme buttons on the homepage.

Small header design fixes

---

src/views/base/navigation/header.astro

We've now had this banner live for nearly 6 months. Let's remove it to leave room for other announcements 👀

chore: remove pfp rename announcement banner

---

src/pages/searchFilters.json.ts

Fixes #1253 
`getAllPosts()` was returning nested/extra posts in collections, including an additional copy of every FFG post.
In comparison, the searchIndex endpoint uses `getPostsByLang("en")`, which does not.

Fix inaccurate tag counts on search when no query is entered

---

src/components/seo/analytics.astro
src/components/seo/seo.astro

Found these while looking through our SEO component. Shouldn't be needed anymore

chore: remove old GA preconnects

---

src/components/collection-card/collection-card.module.scss
src/components/collection-card/collection-card.tsx
src/views/explore/homepage.astro
src/views/search/search-page.tsx

Fixes #1255 
Adds `align-self` so that the collection card button & cover image do not automatically use the max size of the flex container.

Fix collection card sizing on small viewports

---

src/styles/button.scss

Buttons would sometimes auto stretch vertically due to it not having an explicit height value. Particularly in Join Us, as shown below.
While my original fix was local to that page — setting the grid to have an explicit height of min-content, it would've resulted in a whack-a-mole scenario.

Fix button stretching by setting an explicit height value.

---

content/20jasper/posts/javascript-holes-and-tolls/index.md

fix: typos in `javascript` article

---

src/styles/markdown/base.scss
src/styles/markdown/blockquote.scss
src/styles/variables/fonts.scss

Margins were not applying due to the not:([class]) restriction.
Because the classes have been overriden by different headling styles, I've applied the margins to the styles only if within post-body.
Let me know if the code needs to be further optimized.

Article text spacing fix

---

src/pages/collections/art-of-accessibility/index.astro
src/views/collections/framework-field-guide-fundamentals/components/collection-table-of-contents-fundamentals.astro

Removes the "The Art of Accessibility: " label from the marketing homepage's site:

fix: remove prefix labels on A11Y art page

---

src/utils/markdown/components/link-preview/fetchPreviewForUrl.ts
src/utils/markdown/components/link-preview/rehype-transform.ts

Fixes a race condition caused by the link preview component when editing posts in dev mode.
If the same URL is requested multiple times, it can cause a race condition when writing/modifying the image files (specifically when the file is renamed).
This caches `GetPictureResult` and ensures that the function is only called once per URL.

Prevent race condition for link previews in dev mode

---

src/pages/search.astro
src/views/search/search-page.module.scss
src/views/search/search-page.tsx

Fixes #856
This PR moves the `main` & `h1` elements outside the `search-page.tsx` component to the `search.astro` component to improve a11y and SEO.
An effect is now used to toggle the change when the sidebar is shown

Improve search page a11y and seo

---

src/views/collections/framework-field-guide-ecosystem/components/collection-table-of-contents-ecosystem.astro

Closes #1353 
The no outline and outline classes were conflicting. The outline was hidden on hover, but not drag (which I believe would be an active state)
I'm sorry about the formatting--running `pnpm format` did that 😭😭😭
I tested a few states
- does not show outline on hover
- does not show background on drag click
- still visually looks the same
I tested on Firefox and Chrome on windows 10

remove ffg-outlined-button on non anchor chapter descriptors

---

package.json
pnpm-lock.yaml

Pin to astro 5.7 since 5.8 enforces a node version not supported by Vercel (latest version of node 18)
https://astro.build/blog/astro-580/#updated-minimum-nodejs-version

Pin astro to 5.7 to 5.8

---

content/20jasper/posts/iifes-a-javascript-idiom-of-yore/index.md
content/crutchcorn/collections/framework-field-guide-ecosystem/posts/ffg-ecosystem-bundling/index.md
content/crutchcorn/collections/framework-field-guide-ecosystem/posts/ffg-ecosystem-styling/index.md
content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-intro-to-components/index.md
content/crutchcorn/collections/react-beyond-the-render/posts/what-are-react-server-actions/index.md
content/crutchcorn/posts/angular-pipes-a-complete-guide/index.md
content/crutchcorn/posts/react-history-through-code/index.md
content/crutchcorn/posts/setup-a-react-native-monorepo/index.md
content/crutchcorn/posts/web-framework-quickstart-guide/index.md
content/edpratti/posts/figma-compose-line-height/index.md
content/ljtech/collections/web-fundamentals/posts/web-fundamentals-grid/index.md
content/ljtech/collections/web-fundamentals/posts/web-fundamentals-html/index.md
content/ljtech/collections/web-fundamentals/posts/web-fundamentals-javascript-basics/index.md
content/rollbear/posts/compile-time-messages-in-c/index.md
content/tylerlwsmith/posts/build-a-vite-5-backend-integration-with-flask/index.md
src/utils/markdown/createEpubPlugins.ts
src/utils/markdown/createHtmlPlugins.ts
src/utils/markdown/rehype-absolute-paths.ts
src/utils/markdown/rehype-relative-paths.ts

- Fixes misformatted links in ffg-ecosystem-styling
- Removes an empty link from ffg-fundamentals-intro-to-components
- Renames `vitejs.dev` -> `vite.dev`
- Changes any relative post links to absolute `/posts` paths
- Changes rehype-absolute-paths to use the content path as the base URL (handles links to adjacent files, which fixes `./slides.pptx` in angular-templates-start-to-source)

Fix broken links

---

.github/workflows/search-index.yml
.github/workflows/test.yml

Updates the checkout action to use v5. V5 upgrades the action to use node24

update github checkout action to v5

---

package.json

Updates the [node version used by Vercel](https://vercel.com/docs/functions/runtimes/node-js/node-js-versions) to 22.x

Upgrade node version to 22.x

---

src/views/collections/framework-field-guide/components/your-guide-metrics.module.scss
src/views/collections/framework-field-guide/segments/adventure-continues.module.scss

Fixes the issue where on smaller mobile devices, there would be a space to the right of the page that looks like a margin. See #1379
I was not able to replicate the bug on my device because i have a larger screen than the iPhone 12 @20jasper found the bug on, but I did using the inspector. However I had to make the screen a lot smaller (>320 px) to get the same effect.
@20jasper, can you confirm that the issue is fixed on the device? The issue here is that some elements (@crutchcorn metrics & the section on the 'the adventure continues') were wider than the available width.

Fix layout width issues

---

content/ckhackshaw/posts/css-specificity-explained/index.md

Hey there,
I believe the specificity of this example is wrong. Earlier in the post you use `.class.class.class` as `0-3-0`, so this should be the same.
I also tested this against the https://specificity.keegan.st/

Modify details summary in CSS specificity post
